/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateUser,
  GetUsers200,
  GetUsersParams,
  PatchUser,
  Users
} from '../model';





export type getUsersResponse200 = {
  data: GetUsers200
  status: 200
}

export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
;

export type getUsersResponse = (getUsersResponseSuccess)

export const getGetUsersUrl = (params?: GetUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/users?${stringifiedParams}` : `http://localhost:3000/users`
}

/**
 * Retrieve all users with optional filtering and pagination
 * @summary Get all users
 */
export const getUsers = async (params?: GetUsersParams, options?: RequestInit): Promise<getUsersResponse> => {

  const res = await fetch(getGetUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersResponse
}





export const getGetUsersQueryKey = (params?: GetUsersParams,) => {
    return [
    `http://localhost:3000/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = unknown


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params: undefined |  GetUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all users
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postUsersResponse201 = {
  data: Users
  status: 201
}

export type postUsersResponseSuccess = (postUsersResponse201) & {
  headers: Headers;
};
;

export type postUsersResponse = (postUsersResponseSuccess)

export const getPostUsersUrl = () => {




  return `http://localhost:3000/users`
}

/**
 * Add a new user to the system
 * @summary Create a new user
 */
export const postUsers = async (createUser: CreateUser, options?: RequestInit): Promise<postUsersResponse> => {

  const res = await fetch(getPostUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUser)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postUsersResponse
}




export const getPostUsersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,{data: CreateUser}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,{data: CreateUser}, TContext> => {

const mutationKey = ['postUsers'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsers>>, {data: CreateUser}> = (props) => {
          const {data} = props ?? {};

          return  postUsers(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postUsers>>>
    export type PostUsersMutationBody = CreateUser
    export type PostUsersMutationError = unknown

    /**
 * @summary Create a new user
 */
export const usePostUsers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,{data: CreateUser}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsers>>,
        TError,
        {data: CreateUser},
        TContext
      > => {
      return useMutation(getPostUsersMutationOptions(options), queryClient);
    }
    export type getUsersUserIdResponse200 = {
  data: Users
  status: 200
}

export type getUsersUserIdResponseSuccess = (getUsersUserIdResponse200) & {
  headers: Headers;
};
;

export type getUsersUserIdResponse = (getUsersUserIdResponseSuccess)

export const getGetUsersUserIdUrl = (userId: string,) => {




  return `http://localhost:3000/users/${userId}`
}

/**
 * Get user by ID
 * @summary Get user by ID
 */
export const getUsersUserId = async (userId: string, options?: RequestInit): Promise<getUsersUserIdResponse> => {

  const res = await fetch(getGetUsersUserIdUrl(userId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUsersUserIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersUserIdResponse
}





export const getGetUsersUserIdQueryKey = (userId: string,) => {
    return [
    `http://localhost:3000/users/${userId}`
    ] as const;
    }


export const getGetUsersUserIdQueryOptions = <TData = Awaited<ReturnType<typeof getUsersUserId>>, TError = unknown>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersUserId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersUserIdQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersUserId>>> = ({ signal }) => getUsersUserId(userId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersUserId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersUserIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersUserId>>>
export type GetUsersUserIdQueryError = unknown


export function useGetUsersUserId<TData = Awaited<ReturnType<typeof getUsersUserId>>, TError = unknown>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersUserId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersUserId<TData = Awaited<ReturnType<typeof getUsersUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersUserId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserId>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersUserId<TData = Awaited<ReturnType<typeof getUsersUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersUserId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by ID
 */

export function useGetUsersUserId<TData = Awaited<ReturnType<typeof getUsersUserId>>, TError = unknown>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersUserId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersUserIdQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchUsersUserIdResponse200 = {
  data: Users
  status: 200
}

export type patchUsersUserIdResponseSuccess = (patchUsersUserIdResponse200) & {
  headers: Headers;
};
;

export type patchUsersUserIdResponse = (patchUsersUserIdResponseSuccess)

export const getPatchUsersUserIdUrl = (userId: string,) => {




  return `http://localhost:3000/users/${userId}`
}

/**
 * Update user details
 * @summary Update user
 */
export const patchUsersUserId = async (userId: string,
    patchUser: PatchUser, options?: RequestInit): Promise<patchUsersUserIdResponse> => {

  const res = await fetch(getPatchUsersUserIdUrl(userId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchUser)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchUsersUserIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchUsersUserIdResponse
}




export const getPatchUsersUserIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsersUserId>>, TError,{userId: string;data: PatchUser}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchUsersUserId>>, TError,{userId: string;data: PatchUser}, TContext> => {

const mutationKey = ['patchUsersUserId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUsersUserId>>, {userId: string;data: PatchUser}> = (props) => {
          const {userId,data} = props ?? {};

          return  patchUsersUserId(userId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchUsersUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchUsersUserId>>>
    export type PatchUsersUserIdMutationBody = PatchUser
    export type PatchUsersUserIdMutationError = unknown

    /**
 * @summary Update user
 */
export const usePatchUsersUserId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsersUserId>>, TError,{userId: string;data: PatchUser}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUsersUserId>>,
        TError,
        {userId: string;data: PatchUser},
        TContext
      > => {
      return useMutation(getPatchUsersUserIdMutationOptions(options), queryClient);
    }
    export type deleteUsersUserIdResponse204 = {
  data: void
  status: 204
}

export type deleteUsersUserIdResponseSuccess = (deleteUsersUserIdResponse204) & {
  headers: Headers;
};
;

export type deleteUsersUserIdResponse = (deleteUsersUserIdResponseSuccess)

export const getDeleteUsersUserIdUrl = (userId: string,) => {




  return `http://localhost:3000/users/${userId}`
}

/**
 * Remove a user from the system
 * @summary Delete user
 */
export const deleteUsersUserId = async (userId: string, options?: RequestInit): Promise<deleteUsersUserIdResponse> => {

  const res = await fetch(getDeleteUsersUserIdUrl(userId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUsersUserIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteUsersUserIdResponse
}




export const getDeleteUsersUserIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersUserId>>, TError,{userId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersUserId>>, TError,{userId: string}, TContext> => {

const mutationKey = ['deleteUsersUserId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersUserId>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  deleteUsersUserId(userId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersUserId>>>

    export type DeleteUsersUserIdMutationError = unknown

    /**
 * @summary Delete user
 */
export const useDeleteUsersUserId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersUserId>>, TError,{userId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersUserId>>,
        TError,
        {userId: string},
        TContext
      > => {
      return useMutation(getDeleteUsersUserIdMutationOptions(options), queryClient);
    }
