/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateServiceStatuses,
  GetServiceStatus200,
  GetServiceStatusParams,
  PatchServiceStatuses,
  ServiceStatuses
} from '../model';

import { customInstance } from '../../lib/api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all status updates for a service order (timeline)
 * @summary Get service status history
 */
export const getServiceStatus = (
    params?: GetServiceStatusParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetServiceStatus200>(
      {url: `/service-status`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetServiceStatusQueryKey = (params?: GetServiceStatusParams,) => {
    return [
    `/service-status`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetServiceStatusQueryOptions = <TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceStatusQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceStatus>>> = ({ signal }) => getServiceStatus(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceStatus>>>
export type GetServiceStatusQueryError = unknown


export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params: undefined |  GetServiceStatusParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatus>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatus>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get service status history
 */

export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceStatusQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create a status update in the service timeline
 * @summary Add status update to service order
 */
export const postServiceStatus = (
    createServiceStatuses: CreateServiceStatuses,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceStatuses>(
      {url: `/service-status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createServiceStatuses, signal
    },
      options);
    }



export const getPostServiceStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceStatus>>, TError,{data: CreateServiceStatuses}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceStatus>>, TError,{data: CreateServiceStatuses}, TContext> => {

const mutationKey = ['postServiceStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceStatus>>, {data: CreateServiceStatuses}> = (props) => {
          const {data} = props ?? {};

          return  postServiceStatus(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceStatusMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceStatus>>>
    export type PostServiceStatusMutationBody = CreateServiceStatuses
    export type PostServiceStatusMutationError = unknown

    /**
 * @summary Add status update to service order
 */
export const usePostServiceStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceStatus>>, TError,{data: CreateServiceStatuses}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postServiceStatus>>,
        TError,
        {data: CreateServiceStatuses},
        TContext
      > => {
      return useMutation(getPostServiceStatusMutationOptions(options), queryClient);
    }
    /**
 * @summary Get specific status update
 */
export const getServiceStatusServiceStatusId = (
    serviceStatusId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceStatuses>(
      {url: `/service-status/${serviceStatusId}`, method: 'GET', signal
    },
      options);
    }




export const getGetServiceStatusServiceStatusIdQueryKey = (serviceStatusId: string,) => {
    return [
    `/service-status/${serviceStatusId}`
    ] as const;
    }


export const getGetServiceStatusServiceStatusIdQueryOptions = <TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceStatusServiceStatusIdQueryKey(serviceStatusId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>> = ({ signal }) => getServiceStatusServiceStatusId(serviceStatusId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: serviceStatusId !== null && serviceStatusId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceStatusServiceStatusIdQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>>
export type GetServiceStatusServiceStatusIdQueryError = unknown


export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get specific status update
 */

export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceStatusServiceStatusIdQueryOptions(serviceStatusId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update status comment
 */
export const patchServiceStatusServiceStatusId = (
    serviceStatusId: string,
    patchServiceStatuses: PatchServiceStatuses,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceStatuses>(
      {url: `/service-status/${serviceStatusId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchServiceStatuses, signal
    },
      options);
    }



export const getPatchServiceStatusServiceStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, TError,{serviceStatusId: string;data: PatchServiceStatuses}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, TError,{serviceStatusId: string;data: PatchServiceStatuses}, TContext> => {

const mutationKey = ['patchServiceStatusServiceStatusId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, {serviceStatusId: string;data: PatchServiceStatuses}> = (props) => {
          const {serviceStatusId,data} = props ?? {};

          return  patchServiceStatusServiceStatusId(serviceStatusId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchServiceStatusServiceStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>>
    export type PatchServiceStatusServiceStatusIdMutationBody = PatchServiceStatuses
    export type PatchServiceStatusServiceStatusIdMutationError = unknown

    /**
 * @summary Update status comment
 */
export const usePatchServiceStatusServiceStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, TError,{serviceStatusId: string;data: PatchServiceStatuses}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>,
        TError,
        {serviceStatusId: string;data: PatchServiceStatuses},
        TContext
      > => {
      return useMutation(getPatchServiceStatusServiceStatusIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete status update
 */
export const deleteServiceStatusServiceStatusId = (
    serviceStatusId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/service-status/${serviceStatusId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteServiceStatusServiceStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, TError,{serviceStatusId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, TError,{serviceStatusId: string}, TContext> => {

const mutationKey = ['deleteServiceStatusServiceStatusId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, {serviceStatusId: string}> = (props) => {
          const {serviceStatusId} = props ?? {};

          return  deleteServiceStatusServiceStatusId(serviceStatusId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceStatusServiceStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>>

    export type DeleteServiceStatusServiceStatusIdMutationError = unknown

    /**
 * @summary Delete status update
 */
export const useDeleteServiceStatusServiceStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, TError,{serviceStatusId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>,
        TError,
        {serviceStatusId: string},
        TContext
      > => {
      return useMutation(getDeleteServiceStatusServiceStatusIdMutationOptions(options), queryClient);
    }
