/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateServiceStatuses,
  GetServiceStatusParams,
  PatchServiceStatuses,
  ServiceStatuses
} from '../model';





export type getServiceStatusResponse200 = {
  data: ServiceStatuses[]
  status: 200
}

export type getServiceStatusResponseSuccess = (getServiceStatusResponse200) & {
  headers: Headers;
};
;

export type getServiceStatusResponse = (getServiceStatusResponseSuccess)

export const getGetServiceStatusUrl = (params?: GetServiceStatusParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/service-status?${stringifiedParams}` : `http://localhost:3000/service-status`
}

/**
 * Retrieve all status updates for a service order (timeline)
 * @summary Get service status history
 */
export const getServiceStatus = async (params?: GetServiceStatusParams, options?: RequestInit): Promise<getServiceStatusResponse> => {

  const res = await fetch(getGetServiceStatusUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getServiceStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getServiceStatusResponse
}





export const getGetServiceStatusQueryKey = (params?: GetServiceStatusParams,) => {
    return [
    `http://localhost:3000/service-status`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetServiceStatusQueryOptions = <TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceStatusQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceStatus>>> = ({ signal }) => getServiceStatus(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceStatus>>>
export type GetServiceStatusQueryError = unknown


export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params: undefined |  GetServiceStatusParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatus>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatus>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get service status history
 */

export function useGetServiceStatus<TData = Awaited<ReturnType<typeof getServiceStatus>>, TError = unknown>(
 params?: GetServiceStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceStatusQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postServiceStatusResponse201 = {
  data: ServiceStatuses
  status: 201
}

export type postServiceStatusResponseSuccess = (postServiceStatusResponse201) & {
  headers: Headers;
};
;

export type postServiceStatusResponse = (postServiceStatusResponseSuccess)

export const getPostServiceStatusUrl = () => {




  return `http://localhost:3000/service-status`
}

/**
 * Create a status update in the service timeline
 * @summary Add status update to service order
 */
export const postServiceStatus = async (createServiceStatuses: CreateServiceStatuses, options?: RequestInit): Promise<postServiceStatusResponse> => {

  const res = await fetch(getPostServiceStatusUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createServiceStatuses)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postServiceStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postServiceStatusResponse
}




export const getPostServiceStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceStatus>>, TError,{data: CreateServiceStatuses}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceStatus>>, TError,{data: CreateServiceStatuses}, TContext> => {

const mutationKey = ['postServiceStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceStatus>>, {data: CreateServiceStatuses}> = (props) => {
          const {data} = props ?? {};

          return  postServiceStatus(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceStatusMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceStatus>>>
    export type PostServiceStatusMutationBody = CreateServiceStatuses
    export type PostServiceStatusMutationError = unknown

    /**
 * @summary Add status update to service order
 */
export const usePostServiceStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceStatus>>, TError,{data: CreateServiceStatuses}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postServiceStatus>>,
        TError,
        {data: CreateServiceStatuses},
        TContext
      > => {
      return useMutation(getPostServiceStatusMutationOptions(options), queryClient);
    }
    export type getServiceStatusServiceStatusIdResponse200 = {
  data: ServiceStatuses
  status: 200
}

export type getServiceStatusServiceStatusIdResponseSuccess = (getServiceStatusServiceStatusIdResponse200) & {
  headers: Headers;
};
;

export type getServiceStatusServiceStatusIdResponse = (getServiceStatusServiceStatusIdResponseSuccess)

export const getGetServiceStatusServiceStatusIdUrl = (serviceStatusId: string,) => {




  return `http://localhost:3000/service-status/${serviceStatusId}`
}

/**
 * @summary Get specific status update
 */
export const getServiceStatusServiceStatusId = async (serviceStatusId: string, options?: RequestInit): Promise<getServiceStatusServiceStatusIdResponse> => {

  const res = await fetch(getGetServiceStatusServiceStatusIdUrl(serviceStatusId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getServiceStatusServiceStatusIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getServiceStatusServiceStatusIdResponse
}





export const getGetServiceStatusServiceStatusIdQueryKey = (serviceStatusId: string,) => {
    return [
    `http://localhost:3000/service-status/${serviceStatusId}`
    ] as const;
    }


export const getGetServiceStatusServiceStatusIdQueryOptions = <TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceStatusServiceStatusIdQueryKey(serviceStatusId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>> = ({ signal }) => getServiceStatusServiceStatusId(serviceStatusId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: serviceStatusId !== null && serviceStatusId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceStatusServiceStatusIdQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>>
export type GetServiceStatusServiceStatusIdQueryError = unknown


export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>,
          TError,
          Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get specific status update
 */

export function useGetServiceStatusServiceStatusId<TData = Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError = unknown>(
 serviceStatusId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatusServiceStatusId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceStatusServiceStatusIdQueryOptions(serviceStatusId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchServiceStatusServiceStatusIdResponse200 = {
  data: ServiceStatuses
  status: 200
}

export type patchServiceStatusServiceStatusIdResponseSuccess = (patchServiceStatusServiceStatusIdResponse200) & {
  headers: Headers;
};
;

export type patchServiceStatusServiceStatusIdResponse = (patchServiceStatusServiceStatusIdResponseSuccess)

export const getPatchServiceStatusServiceStatusIdUrl = (serviceStatusId: string,) => {




  return `http://localhost:3000/service-status/${serviceStatusId}`
}

/**
 * @summary Update status comment
 */
export const patchServiceStatusServiceStatusId = async (serviceStatusId: string,
    patchServiceStatuses: PatchServiceStatuses, options?: RequestInit): Promise<patchServiceStatusServiceStatusIdResponse> => {

  const res = await fetch(getPatchServiceStatusServiceStatusIdUrl(serviceStatusId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchServiceStatuses)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchServiceStatusServiceStatusIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchServiceStatusServiceStatusIdResponse
}




export const getPatchServiceStatusServiceStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, TError,{serviceStatusId: string;data: PatchServiceStatuses}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, TError,{serviceStatusId: string;data: PatchServiceStatuses}, TContext> => {

const mutationKey = ['patchServiceStatusServiceStatusId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, {serviceStatusId: string;data: PatchServiceStatuses}> = (props) => {
          const {serviceStatusId,data} = props ?? {};

          return  patchServiceStatusServiceStatusId(serviceStatusId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchServiceStatusServiceStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>>
    export type PatchServiceStatusServiceStatusIdMutationBody = PatchServiceStatuses
    export type PatchServiceStatusServiceStatusIdMutationError = unknown

    /**
 * @summary Update status comment
 */
export const usePatchServiceStatusServiceStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>, TError,{serviceStatusId: string;data: PatchServiceStatuses}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchServiceStatusServiceStatusId>>,
        TError,
        {serviceStatusId: string;data: PatchServiceStatuses},
        TContext
      > => {
      return useMutation(getPatchServiceStatusServiceStatusIdMutationOptions(options), queryClient);
    }
    export type deleteServiceStatusServiceStatusIdResponse204 = {
  data: void
  status: 204
}

export type deleteServiceStatusServiceStatusIdResponseSuccess = (deleteServiceStatusServiceStatusIdResponse204) & {
  headers: Headers;
};
;

export type deleteServiceStatusServiceStatusIdResponse = (deleteServiceStatusServiceStatusIdResponseSuccess)

export const getDeleteServiceStatusServiceStatusIdUrl = (serviceStatusId: string,) => {




  return `http://localhost:3000/service-status/${serviceStatusId}`
}

/**
 * @summary Delete status update
 */
export const deleteServiceStatusServiceStatusId = async (serviceStatusId: string, options?: RequestInit): Promise<deleteServiceStatusServiceStatusIdResponse> => {

  const res = await fetch(getDeleteServiceStatusServiceStatusIdUrl(serviceStatusId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteServiceStatusServiceStatusIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteServiceStatusServiceStatusIdResponse
}




export const getDeleteServiceStatusServiceStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, TError,{serviceStatusId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, TError,{serviceStatusId: string}, TContext> => {

const mutationKey = ['deleteServiceStatusServiceStatusId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, {serviceStatusId: string}> = (props) => {
          const {serviceStatusId} = props ?? {};

          return  deleteServiceStatusServiceStatusId(serviceStatusId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceStatusServiceStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>>

    export type DeleteServiceStatusServiceStatusIdMutationError = unknown

    /**
 * @summary Delete status update
 */
export const useDeleteServiceStatusServiceStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>, TError,{serviceStatusId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteServiceStatusServiceStatusId>>,
        TError,
        {serviceStatusId: string},
        TContext
      > => {
      return useMutation(getDeleteServiceStatusServiceStatusIdMutationOptions(options), queryClient);
    }
