/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Contacts,
  CreateContact,
  GetContacts200,
  GetContactsParams,
  PatchContact
} from '../model';





export type getContactsResponse200 = {
  data: GetContacts200
  status: 200
}

export type getContactsResponseSuccess = (getContactsResponse200) & {
  headers: Headers;
};
;

export type getContactsResponse = (getContactsResponseSuccess)

export const getGetContactsUrl = (params?: GetContactsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/contacts?${stringifiedParams}` : `http://localhost:3000/contacts`
}

/**
 * Retrieve all contacts with optional filtering
 * @summary Get all contacts
 */
export const getContacts = async (params?: GetContactsParams, options?: RequestInit): Promise<getContactsResponse> => {

  const res = await fetch(getGetContactsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getContactsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getContactsResponse
}





export const getGetContactsQueryKey = (params?: GetContactsParams,) => {
    return [
    `http://localhost:3000/contacts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetContactsQueryOptions = <TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContacts>>> = ({ signal }) => getContacts(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsQueryResult = NonNullable<Awaited<ReturnType<typeof getContacts>>>
export type GetContactsQueryError = unknown


export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params: undefined |  GetContactsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContacts>>,
          TError,
          Awaited<ReturnType<typeof getContacts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContacts>>,
          TError,
          Awaited<ReturnType<typeof getContacts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all contacts
 */

export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postContactsResponse201 = {
  data: Contacts
  status: 201
}

export type postContactsResponseSuccess = (postContactsResponse201) & {
  headers: Headers;
};
;

export type postContactsResponse = (postContactsResponseSuccess)

export const getPostContactsUrl = () => {




  return `http://localhost:3000/contacts`
}

/**
 * @summary Create contact
 */
export const postContacts = async (createContact: CreateContact, options?: RequestInit): Promise<postContactsResponse> => {

  const res = await fetch(getPostContactsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createContact)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postContactsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postContactsResponse
}




export const getPostContactsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postContacts>>, TError,{data: CreateContact}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postContacts>>, TError,{data: CreateContact}, TContext> => {

const mutationKey = ['postContacts'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postContacts>>, {data: CreateContact}> = (props) => {
          const {data} = props ?? {};

          return  postContacts(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostContactsMutationResult = NonNullable<Awaited<ReturnType<typeof postContacts>>>
    export type PostContactsMutationBody = CreateContact
    export type PostContactsMutationError = unknown

    /**
 * @summary Create contact
 */
export const usePostContacts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postContacts>>, TError,{data: CreateContact}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postContacts>>,
        TError,
        {data: CreateContact},
        TContext
      > => {
      return useMutation(getPostContactsMutationOptions(options), queryClient);
    }
    export type getContactsContactIdResponse200 = {
  data: Contacts
  status: 200
}

export type getContactsContactIdResponseSuccess = (getContactsContactIdResponse200) & {
  headers: Headers;
};
;

export type getContactsContactIdResponse = (getContactsContactIdResponseSuccess)

export const getGetContactsContactIdUrl = (contactId: string,) => {




  return `http://localhost:3000/contacts/${contactId}`
}

/**
 * Get contact by ID
 * @summary Get contact by ID
 */
export const getContactsContactId = async (contactId: string, options?: RequestInit): Promise<getContactsContactIdResponse> => {

  const res = await fetch(getGetContactsContactIdUrl(contactId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getContactsContactIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getContactsContactIdResponse
}





export const getGetContactsContactIdQueryKey = (contactId: string,) => {
    return [
    `http://localhost:3000/contacts/${contactId}`
    ] as const;
    }


export const getGetContactsContactIdQueryOptions = <TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsContactIdQueryKey(contactId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactsContactId>>> = ({ signal }) => getContactsContactId(contactId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: contactId !== null && contactId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsContactIdQueryResult = NonNullable<Awaited<ReturnType<typeof getContactsContactId>>>
export type GetContactsContactIdQueryError = unknown


export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsContactId>>,
          TError,
          Awaited<ReturnType<typeof getContactsContactId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsContactId>>,
          TError,
          Awaited<ReturnType<typeof getContactsContactId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact by ID
 */

export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsContactIdQueryOptions(contactId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchContactsContactIdResponse200 = {
  data: Contacts
  status: 200
}

export type patchContactsContactIdResponseSuccess = (patchContactsContactIdResponse200) & {
  headers: Headers;
};
;

export type patchContactsContactIdResponse = (patchContactsContactIdResponseSuccess)

export const getPatchContactsContactIdUrl = (contactId: string,) => {




  return `http://localhost:3000/contacts/${contactId}`
}

/**
 * @summary Update contact
 */
export const patchContactsContactId = async (contactId: string,
    patchContact: PatchContact, options?: RequestInit): Promise<patchContactsContactIdResponse> => {

  const res = await fetch(getPatchContactsContactIdUrl(contactId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchContact)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchContactsContactIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchContactsContactIdResponse
}




export const getPatchContactsContactIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchContactsContactId>>, TError,{contactId: string;data: PatchContact}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchContactsContactId>>, TError,{contactId: string;data: PatchContact}, TContext> => {

const mutationKey = ['patchContactsContactId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchContactsContactId>>, {contactId: string;data: PatchContact}> = (props) => {
          const {contactId,data} = props ?? {};

          return  patchContactsContactId(contactId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchContactsContactIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchContactsContactId>>>
    export type PatchContactsContactIdMutationBody = PatchContact
    export type PatchContactsContactIdMutationError = unknown

    /**
 * @summary Update contact
 */
export const usePatchContactsContactId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchContactsContactId>>, TError,{contactId: string;data: PatchContact}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchContactsContactId>>,
        TError,
        {contactId: string;data: PatchContact},
        TContext
      > => {
      return useMutation(getPatchContactsContactIdMutationOptions(options), queryClient);
    }
    export type deleteContactsContactIdResponse204 = {
  data: void
  status: 204
}

export type deleteContactsContactIdResponseSuccess = (deleteContactsContactIdResponse204) & {
  headers: Headers;
};
;

export type deleteContactsContactIdResponse = (deleteContactsContactIdResponseSuccess)

export const getDeleteContactsContactIdUrl = (contactId: string,) => {




  return `http://localhost:3000/contacts/${contactId}`
}

/**
 * @summary Delete contact
 */
export const deleteContactsContactId = async (contactId: string, options?: RequestInit): Promise<deleteContactsContactIdResponse> => {

  const res = await fetch(getDeleteContactsContactIdUrl(contactId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteContactsContactIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteContactsContactIdResponse
}




export const getDeleteContactsContactIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactsContactId>>, TError,{contactId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContactsContactId>>, TError,{contactId: string}, TContext> => {

const mutationKey = ['deleteContactsContactId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContactsContactId>>, {contactId: string}> = (props) => {
          const {contactId} = props ?? {};

          return  deleteContactsContactId(contactId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactsContactIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContactsContactId>>>

    export type DeleteContactsContactIdMutationError = unknown

    /**
 * @summary Delete contact
 */
export const useDeleteContactsContactId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactsContactId>>, TError,{contactId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContactsContactId>>,
        TError,
        {contactId: string},
        TContext
      > => {
      return useMutation(getDeleteContactsContactIdMutationOptions(options), queryClient);
    }
