/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Contacts,
  CreateContact,
  GetContacts200,
  GetContactsParams,
  PatchContact
} from '../model';

import { customInstance } from '../../lib/api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all contacts with optional filtering
 * @summary Get all contacts
 */
export const getContacts = (
    params?: GetContactsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetContacts200>(
      {url: `/contacts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetContactsQueryKey = (params?: GetContactsParams,) => {
    return [
    `/contacts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetContactsQueryOptions = <TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContacts>>> = ({ signal }) => getContacts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsQueryResult = NonNullable<Awaited<ReturnType<typeof getContacts>>>
export type GetContactsQueryError = unknown


export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params: undefined |  GetContactsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContacts>>,
          TError,
          Awaited<ReturnType<typeof getContacts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContacts>>,
          TError,
          Awaited<ReturnType<typeof getContacts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all contacts
 */

export function useGetContacts<TData = Awaited<ReturnType<typeof getContacts>>, TError = unknown>(
 params?: GetContactsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContacts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create contact
 */
export const postContacts = (
    createContact: CreateContact,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Contacts>(
      {url: `/contacts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContact, signal
    },
      options);
    }



export const getPostContactsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postContacts>>, TError,{data: CreateContact}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postContacts>>, TError,{data: CreateContact}, TContext> => {

const mutationKey = ['postContacts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postContacts>>, {data: CreateContact}> = (props) => {
          const {data} = props ?? {};

          return  postContacts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostContactsMutationResult = NonNullable<Awaited<ReturnType<typeof postContacts>>>
    export type PostContactsMutationBody = CreateContact
    export type PostContactsMutationError = unknown

    /**
 * @summary Create contact
 */
export const usePostContacts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postContacts>>, TError,{data: CreateContact}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postContacts>>,
        TError,
        {data: CreateContact},
        TContext
      > => {
      return useMutation(getPostContactsMutationOptions(options), queryClient);
    }
    /**
 * Get contact by ID
 * @summary Get contact by ID
 */
export const getContactsContactId = (
    contactId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Contacts>(
      {url: `/contacts/${contactId}`, method: 'GET', signal
    },
      options);
    }




export const getGetContactsContactIdQueryKey = (contactId: string,) => {
    return [
    `/contacts/${contactId}`
    ] as const;
    }


export const getGetContactsContactIdQueryOptions = <TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsContactIdQueryKey(contactId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactsContactId>>> = ({ signal }) => getContactsContactId(contactId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: contactId !== null && contactId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsContactIdQueryResult = NonNullable<Awaited<ReturnType<typeof getContactsContactId>>>
export type GetContactsContactIdQueryError = unknown


export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsContactId>>,
          TError,
          Awaited<ReturnType<typeof getContactsContactId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsContactId>>,
          TError,
          Awaited<ReturnType<typeof getContactsContactId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact by ID
 */

export function useGetContactsContactId<TData = Awaited<ReturnType<typeof getContactsContactId>>, TError = unknown>(
 contactId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsContactIdQueryOptions(contactId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update contact
 */
export const patchContactsContactId = (
    contactId: string,
    patchContact: PatchContact,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Contacts>(
      {url: `/contacts/${contactId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchContact, signal
    },
      options);
    }



export const getPatchContactsContactIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchContactsContactId>>, TError,{contactId: string;data: PatchContact}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchContactsContactId>>, TError,{contactId: string;data: PatchContact}, TContext> => {

const mutationKey = ['patchContactsContactId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchContactsContactId>>, {contactId: string;data: PatchContact}> = (props) => {
          const {contactId,data} = props ?? {};

          return  patchContactsContactId(contactId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchContactsContactIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchContactsContactId>>>
    export type PatchContactsContactIdMutationBody = PatchContact
    export type PatchContactsContactIdMutationError = unknown

    /**
 * @summary Update contact
 */
export const usePatchContactsContactId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchContactsContactId>>, TError,{contactId: string;data: PatchContact}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchContactsContactId>>,
        TError,
        {contactId: string;data: PatchContact},
        TContext
      > => {
      return useMutation(getPatchContactsContactIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete contact
 */
export const deleteContactsContactId = (
    contactId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/contacts/${contactId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteContactsContactIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactsContactId>>, TError,{contactId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContactsContactId>>, TError,{contactId: string}, TContext> => {

const mutationKey = ['deleteContactsContactId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContactsContactId>>, {contactId: string}> = (props) => {
          const {contactId} = props ?? {};

          return  deleteContactsContactId(contactId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactsContactIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContactsContactId>>>

    export type DeleteContactsContactIdMutationError = unknown

    /**
 * @summary Delete contact
 */
export const useDeleteContactsContactId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactsContactId>>, TError,{contactId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContactsContactId>>,
        TError,
        {contactId: string},
        TContext
      > => {
      return useMutation(getDeleteContactsContactIdMutationOptions(options), queryClient);
    }
