/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateServiceOrderIssueDescription } from './createServiceOrderIssueDescription';

export interface CreateServiceOrder {
  userProductId: string;
  /** @minimum 0 */
  estimatedPrice?: number;
  /**
     * @minimum 1
     * @maximum 5
     */
  priorityLevel?: number;
  estimatedCompletionDate?: string;
  issueDescription: CreateServiceOrderIssueDescription;
  issueNotes?: string;
  /** Must be a servicer or admin user */
  entryBy: string;
}
