/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardMetricsCompleted } from './dashboardMetricsCompleted';
import type { DashboardMetricsDelivered } from './dashboardMetricsDelivered';
import type { DashboardMetricsReceived } from './dashboardMetricsReceived';

export interface DashboardMetrics {
  /** Orders created in the current period */
  received: DashboardMetricsReceived;
  /** Orders whose latest status is not DELIVERED or CANCELLED (no status = RECEIVED) */
  open: number;
  /** Orders that got a COMPLETED status entry in the period (counted once per order) */
  completed: DashboardMetricsCompleted;
  /** Orders that got a DELIVERED status entry in the period */
  delivered: DashboardMetricsDelivered;
  /** Same rule as GET /service-orders?overdue=true */
  overdue: number;
  /** Orders whose latest status is COMPLETED (repair done, not yet delivered) */
  awaitingPickup: number;
}
