/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export type GetProductsParams = {
/**
 * Filter by product name
 */
productName?: string;
/**
 * Filter by brand
 */
brandId?: string;
/**
 * Filter by product type
 */
productTypeId?: string;
page?: number;
limit?: number;
};
