/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { GetServiceOrdersIssueDescription } from './getServiceOrdersIssueDescription';
import type { GetServiceOrdersPaymentMethod } from './getServiceOrdersPaymentMethod';
import type { GetServiceOrdersPaymentStatus } from './getServiceOrdersPaymentStatus';

export type GetServiceOrdersParams = {
/**
 * Partial tag number match — digits anywhere in the tag (`0004` finds `260004`)
 * @pattern ^[0-9]{1,6}$
 */
tagSearch?: string;
/**
 * Latest repair status name (e.g. IN_PROGRESS). Orders with no status entry match RECEIVED.
 */
status?: string;
/**
 * Filter by userProductId
 */
userProductId?: string;
/**
 * Payment method used
 */
paymentMethod?: GetServiceOrdersPaymentMethod;
/**
 * Payment status
 */
paymentStatus?: GetServiceOrdersPaymentStatus;
/**
 * Priority level (1=highest, 5=lowest)
 * @minimum 1
 * @maximum 5
 */
priorityLevel?: number;
issueDescription?: GetServiceOrdersIssueDescription;
/**
 * Filter by entered by service order person
 */
entryBy?: string;
/**
 * Orders for devices owned by this customer
 */
userId?: string;
page?: number;
limit?: number;
};
