/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export type GetServiceOrderComposerSearchParams = {
/**
 * Search by customer name
 */
userName?: string;
/**
 * Search by contact number prefix
 */
contactNumber?: string;
/**
 * Search by email
 */
email?: string;
/**
 * Search by product name
 */
productName?: string;
/**
 * Search by brand name
 */
brandName?: string;
/**
 * Search by product type name
 */
productTypeName?: string;
/**
 * Search by serial number prefix
 */
serialNumber?: string;
/**
 * Maximum number of contexts to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
