/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { GetServiceOrdersIssueDescription } from './getServiceOrdersIssueDescription';
import type { GetServiceOrdersPaymentMethod } from './getServiceOrdersPaymentMethod';
import type { GetServiceOrdersPaymentStatus } from './getServiceOrdersPaymentStatus';
import type { GetServiceOrdersStatus } from './getServiceOrdersStatus';

export type GetServiceOrdersParams = {
/**
 * Filter by tagNo
 * @minimum 0
 * @maximum 999999
 */
tagNo?: number;
/**
 * Filter by userProductId
 */
userProductId?: string;
/**
 * Payment method used
 */
paymentMethod?: GetServiceOrdersPaymentMethod;
/**
 * Payment status
 */
paymentStatus?: GetServiceOrdersPaymentStatus;
/**
 * Priority level (1=highest, 5=lowest)
 * @minimum 1
 * @maximum 5
 */
priorityLevel?: number;
estimatedCompletionDate?: string;
actualCompletionDate?: string;
issueDescription?: GetServiceOrdersIssueDescription;
/**
 * Filter by status
 */
status?: GetServiceOrdersStatus;
/**
 * Filter by entered by service order person
 */
entryBy?: string;
page?: number;
limit?: number;
};
