/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchServiceOrderIssueDescription } from './patchServiceOrderIssueDescription';
import type { PatchServiceOrderPaymentMethod } from './patchServiceOrderPaymentMethod';
import type { PatchServiceOrderPaymentStatus } from './patchServiceOrderPaymentStatus';

export interface PatchServiceOrder {
  userProductId?: string;
  /** @minimum 0 */
  estimatedPrice?: number;
  /** @minimum 0 */
  finalPrice?: number;
  paymentMethod?: PatchServiceOrderPaymentMethod;
  paymentStatus?: PatchServiceOrderPaymentStatus;
  /**
     * @minimum 1
     * @maximum 5
     */
  priorityLevel?: number;
  estimatedCompletionDate?: string;
  actualCompletionDate?: string;
  issueDescription?: PatchServiceOrderIssueDescription;
  issueNotes?: string;
}
