/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Send only the fields to change. `null` clears email or address.
 */
export interface PatchUser {
  /** @minLength 1 */
  userName?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  address?: string | null;
  roleId?: number;
}
