/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { Brands } from './brands';
import type { ProductTypes } from './productTypes';

export interface Products {
  productId?: string;
  productName?: string;
  description?: string;
  brand?: Brands;
  product_type?: ProductTypes;
  createdAt?: string;
  updatedAt?: string;
}
