/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export interface Roles {
  /** Unique role identifier */
  roleId?: number;
  /** Name of the role (e.g., customer, servicer, customer_servicer, b2b_customer) */
  roleName?: string;
  /** Whether this role can perform service work */
  isServicer?: boolean;
  /** Whether this role can be a customer */
  isCustomer?: boolean;
  /** Whether this role is a B2B business entity */
  isBusiness?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
