/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payment method used
 * @nullable
 */
export type ServiceOrdersPaymentMethod = typeof ServiceOrdersPaymentMethod[keyof typeof ServiceOrdersPaymentMethod] | null;


export const ServiceOrdersPaymentMethod = {
  CASH: 'CASH',
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  ONLINE_PAYMENT: 'ONLINE_PAYMENT',
  OTHER: 'OTHER',
} as const;
