/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceOrdersIssueDescription } from './serviceOrdersIssueDescription';
import type { ServiceOrdersPaymentMethod } from './serviceOrdersPaymentMethod';
import type { ServiceOrdersPaymentStatus } from './serviceOrdersPaymentStatus';
import type { UserProducts } from './userProducts';
import type { Users } from './users';

export interface ServiceOrders {
  serviceOrderId?: string;
  /** Auto-generated order number (YYDDDD format, e.g., 260001) */
  tagNo?: number;
  userProduct?: UserProducts;
  /** Estimated repair cost */
  estimatedPrice?: number;
  /** Final repair cost */
  finalPrice?: number;
  /** Payment method used */
  paymentMethod?: ServiceOrdersPaymentMethod;
  /** Payment status */
  paymentStatus?: ServiceOrdersPaymentStatus;
  /**
     * Priority level (1=highest, 5=lowest)
     * @minimum 1
     * @maximum 5
     */
  priorityLevel?: number;
  estimatedCompletionDate?: string;
  actualCompletionDate?: string;
  /** Type of issue */
  issueDescription?: ServiceOrdersIssueDescription;
  /** Detailed notes about the issue */
  issueNotes?: string;
  entryBy?: Users;
  createdAt?: string;
  updatedAt?: string;
}
