/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceOrders } from './serviceOrders';
import type { Statuses } from './statuses';
import type { Users } from './users';

export interface ServiceStatuses {
  serviceStatusId?: string;
  serviceOrder?: ServiceOrders;
  status?: Statuses;
  assignedTo?: Users;
  /** Status update comments */
  comment?: string;
  /** Whether customer should be notified */
  notifyCustomer?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
