/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceStatuses {
  serviceStatusId?: string;
  serviceOrderId?: string;
  statusId?: string;
  /** Display name of the status */
  statusName?: string;
  assignedTo?: string;
  /** Name of the assigned staff member */
  assignedToName?: string;
  /**
     * Status update comments
     * @nullable
     */
  comment?: string | null;
  /** Whether customer should be notified */
  notifyCustomer?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
