/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceOrdersIssueDescription } from './serviceOrdersIssueDescription';
import type { ServiceOrdersPaymentMethod } from './serviceOrdersPaymentMethod';
import type { ServiceOrdersPaymentStatus } from './serviceOrdersPaymentStatus';

export interface ServiceOrders {
  serviceOrderId?: string;
  /** Auto-generated order number (YYDDDD format, e.g., 260001) */
  tagNo?: number;
  /** Device this order services */
  userProductId?: string;
  /**
     * Estimated repair cost
     * @nullable
     */
  estimatedPrice?: number | null;
  /**
     * Final repair cost
     * @nullable
     */
  finalPrice?: number | null;
  /**
     * Payment method used
     * @nullable
     */
  paymentMethod?: ServiceOrdersPaymentMethod;
  /** Payment status */
  paymentStatus?: ServiceOrdersPaymentStatus;
  /**
     * Priority level (1=highest, 5=lowest)
     * @minimum 1
     * @maximum 5
     */
  priorityLevel?: number;
  /** @nullable */
  estimatedCompletionDate?: string | null;
  /** @nullable */
  actualCompletionDate?: string | null;
  /** Type of issue */
  issueDescription?: ServiceOrdersIssueDescription;
  /**
     * Detailed notes about the issue
     * @nullable
     */
  issueNotes?: string | null;
  /** Staff user who logged the order */
  entryBy?: string;
  createdAt?: string;
  updatedAt?: string;
  /** Customer who owns the device */
  userId?: string;
  /** Customer name */
  userName?: string;
  /**
     * Customer's primary contact number
     * @nullable
     */
  contactNumber?: string | null;
  /** Device product name */
  productName?: string;
  /** Device brand */
  brandName?: string;
  /** Device serial number */
  serialNumber?: string;
  /**
     * Latest status entry, if any
     * @nullable
     */
  currentStatus?: string | null;
}
