/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export interface Statuses {
  statusId?: string;
  /** Status name (e.g., PENDING, IN_PROGRESS, COMPLETED, ON_HOLD) */
  statusName?: string;
  createdAt?: string;
  updatedAt?: string;
}
