/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';

export interface Users {
  /** Unique user identifier */
  userId?: string;
  /** Usersname (must be unique) */
  userName?: string;
  /** Users email address (must be unique) */
  email?: string;
  /** Users's physical address */
  address?: string;
  role?: Roles;
  createdAt?: string;
  updatedAt?: string;
}
