/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import type { Products } from './products';
import type { Users } from './users';

export interface UserProducts {
  userProductId?: string;
  user?: Users;
  product?: Products;
  /** Unique serial number */
  serialNumber?: string;
  /** Encrypted password for the device */
  loginPassword?: string;
  /** Extra information (e.g., RAM, Storage specs) */
  additionalInfo?: string;
  createdAt?: string;
  updatedAt?: string;
}
