/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export interface UserProducts {
  userProductId?: string;
  /** Owner of the device */
  userId?: string;
  /** Product model of the device */
  productId?: string;
  /** Unique serial number */
  serialNumber?: string;
  /**
     * Device login password, if the customer provided one
     * @nullable
     */
  loginPassword?: string | null;
  /**
     * Extra information (e.g., RAM, Storage specs)
     * @nullable
     */
  additionalInfo?: string | null;
  createdAt?: string;
  updatedAt?: string;
}
