/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */

export interface Users {
  /** Unique user identifier */
  userId?: string;
  /** Customer or staff name */
  userName?: string;
  /**
     * Email address (unique when present)
     * @nullable
     */
  email?: string | null;
  /**
     * Physical address
     * @nullable
     */
  address?: string | null;
  /** Role of the user */
  roleId?: number;
  createdAt?: string;
  updatedAt?: string;
}
