/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProduct,
  CreateUserProduct,
  GetProducts200,
  GetProductsParams,
  GetUserProducts200,
  GetUserProductsParams,
  PatchProduct,
  PatchUserProduct,
  Products,
  UserProducts
} from '../model';

import { customInstance } from '../../lib/api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all Products with optional filtering
 * @summary Get all Products
 */
export const getProducts = (
    params?: GetProductsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetProducts200>(
      {url: `/products`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetProductsQueryKey = (params?: GetProductsParams,) => {
    return [
    `/products`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) => getProducts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = unknown


export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params: undefined |  GetProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Products
 */

export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create product
 */
export const postProducts = (
    createProduct: CreateProduct,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Products>(
      {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProduct, signal
    },
      options);
    }



export const getPostProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: CreateProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: CreateProduct}, TContext> => {

const mutationKey = ['postProducts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProducts>>, {data: CreateProduct}> = (props) => {
          const {data} = props ?? {};

          return  postProducts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postProducts>>>
    export type PostProductsMutationBody = CreateProduct
    export type PostProductsMutationError = unknown

    /**
 * @summary Create product
 */
export const usePostProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: CreateProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProducts>>,
        TError,
        {data: CreateProduct},
        TContext
      > => {
      return useMutation(getPostProductsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get product by ID
 */
export const getProductsProductId = (
    productId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Products>(
      {url: `/products/${productId}`, method: 'GET', signal
    },
      options);
    }




export const getGetProductsProductIdQueryKey = (productId: string,) => {
    return [
    `/products/${productId}`
    ] as const;
    }


export const getGetProductsProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsProductIdQueryKey(productId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductsProductId>>> = ({ signal }) => getProductsProductId(productId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: productId !== null && productId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsProductId>>>
export type GetProductsProductIdQueryError = unknown


export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsProductId>>,
          TError,
          Awaited<ReturnType<typeof getProductsProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsProductId>>,
          TError,
          Awaited<ReturnType<typeof getProductsProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product by ID
 */

export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsProductIdQueryOptions(productId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update product
 */
export const patchProductsProductId = (
    productId: string,
    patchProduct: PatchProduct,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Products>(
      {url: `/products/${productId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchProduct, signal
    },
      options);
    }



export const getPatchProductsProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchProductsProductId>>, TError,{productId: string;data: PatchProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchProductsProductId>>, TError,{productId: string;data: PatchProduct}, TContext> => {

const mutationKey = ['patchProductsProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchProductsProductId>>, {productId: string;data: PatchProduct}> = (props) => {
          const {productId,data} = props ?? {};

          return  patchProductsProductId(productId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchProductsProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchProductsProductId>>>
    export type PatchProductsProductIdMutationBody = PatchProduct
    export type PatchProductsProductIdMutationError = unknown

    /**
 * @summary Update product
 */
export const usePatchProductsProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchProductsProductId>>, TError,{productId: string;data: PatchProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchProductsProductId>>,
        TError,
        {productId: string;data: PatchProduct},
        TContext
      > => {
      return useMutation(getPatchProductsProductIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete product
 */
export const deleteProductsProductId = (
    productId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/products/${productId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteProductsProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductsProductId>>, TError,{productId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProductsProductId>>, TError,{productId: string}, TContext> => {

const mutationKey = ['deleteProductsProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProductsProductId>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  deleteProductsProductId(productId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductsProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProductsProductId>>>

    export type DeleteProductsProductIdMutationError = unknown

    /**
 * @summary Delete product
 */
export const useDeleteProductsProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductsProductId>>, TError,{productId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProductsProductId>>,
        TError,
        {productId: string},
        TContext
      > => {
      return useMutation(getDeleteProductsProductIdMutationOptions(options), queryClient);
    }
    /**
 * Retrieve user Products with optional filtering
 * @summary Get all user Products
 */
export const getUserProducts = (
    params?: GetUserProductsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetUserProducts200>(
      {url: `/user-products`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetUserProductsQueryKey = (params?: GetUserProductsParams,) => {
    return [
    `/user-products`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUserProductsQueryOptions = <TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProducts>>> = ({ signal }) => getUserProducts(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProducts>>>
export type GetUserProductsQueryError = unknown


export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params: undefined |  GetUserProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProducts>>,
          TError,
          Awaited<ReturnType<typeof getUserProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProducts>>,
          TError,
          Awaited<ReturnType<typeof getUserProducts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all user Products
 */

export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create user product
 */
export const postUserProducts = (
    createUserProduct: CreateUserProduct,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserProducts>(
      {url: `/user-products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserProduct, signal
    },
      options);
    }



export const getPostUserProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUserProducts>>, TError,{data: CreateUserProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUserProducts>>, TError,{data: CreateUserProduct}, TContext> => {

const mutationKey = ['postUserProducts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUserProducts>>, {data: CreateUserProduct}> = (props) => {
          const {data} = props ?? {};

          return  postUserProducts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUserProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postUserProducts>>>
    export type PostUserProductsMutationBody = CreateUserProduct
    export type PostUserProductsMutationError = unknown

    /**
 * @summary Create user product
 */
export const usePostUserProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUserProducts>>, TError,{data: CreateUserProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUserProducts>>,
        TError,
        {data: CreateUserProduct},
        TContext
      > => {
      return useMutation(getPostUserProductsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get user product by ID
 */
export const getUserProductsUserProductId = (
    userProductId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserProducts>(
      {url: `/user-products/${userProductId}`, method: 'GET', signal
    },
      options);
    }




export const getGetUserProductsUserProductIdQueryKey = (userProductId: string,) => {
    return [
    `/user-products/${userProductId}`
    ] as const;
    }


export const getGetUserProductsUserProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProductsUserProductIdQueryKey(userProductId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProductsUserProductId>>> = ({ signal }) => getUserProductsUserProductId(userProductId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userProductId !== null && userProductId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProductsUserProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProductsUserProductId>>>
export type GetUserProductsUserProductIdQueryError = unknown


export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProductsUserProductId>>,
          TError,
          Awaited<ReturnType<typeof getUserProductsUserProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProductsUserProductId>>,
          TError,
          Awaited<ReturnType<typeof getUserProductsUserProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user product by ID
 */

export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProductsUserProductIdQueryOptions(userProductId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update user product
 */
export const patchUserProductsUserProductId = (
    userProductId: string,
    patchUserProduct: PatchUserProduct,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserProducts>(
      {url: `/user-products/${userProductId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchUserProduct, signal
    },
      options);
    }



export const getPatchUserProductsUserProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, TError,{userProductId: string;data: PatchUserProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, TError,{userProductId: string;data: PatchUserProduct}, TContext> => {

const mutationKey = ['patchUserProductsUserProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, {userProductId: string;data: PatchUserProduct}> = (props) => {
          const {userProductId,data} = props ?? {};

          return  patchUserProductsUserProductId(userProductId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchUserProductsUserProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchUserProductsUserProductId>>>
    export type PatchUserProductsUserProductIdMutationBody = PatchUserProduct
    export type PatchUserProductsUserProductIdMutationError = unknown

    /**
 * @summary Update user product
 */
export const usePatchUserProductsUserProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, TError,{userProductId: string;data: PatchUserProduct}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUserProductsUserProductId>>,
        TError,
        {userProductId: string;data: PatchUserProduct},
        TContext
      > => {
      return useMutation(getPatchUserProductsUserProductIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete user product
 */
export const deleteUserProductsUserProductId = (
    userProductId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/user-products/${userProductId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteUserProductsUserProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, TError,{userProductId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, TError,{userProductId: string}, TContext> => {

const mutationKey = ['deleteUserProductsUserProductId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, {userProductId: string}> = (props) => {
          const {userProductId} = props ?? {};

          return  deleteUserProductsUserProductId(userProductId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserProductsUserProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>>

    export type DeleteUserProductsUserProductIdMutationError = unknown

    /**
 * @summary Delete user product
 */
export const useDeleteUserProductsUserProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, TError,{userProductId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserProductsUserProductId>>,
        TError,
        {userProductId: string},
        TContext
      > => {
      return useMutation(getDeleteUserProductsUserProductIdMutationOptions(options), queryClient);
    }
