/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProduct,
  CreateUserProduct,
  GetProducts200,
  GetProductsParams,
  GetUserProducts200,
  GetUserProductsParams,
  PatchProduct,
  PatchUserProduct,
  Products,
  UserProducts
} from '../model';





export type getProductsResponse200 = {
  data: GetProducts200
  status: 200
}

export type getProductsResponseSuccess = (getProductsResponse200) & {
  headers: Headers;
};
;

export type getProductsResponse = (getProductsResponseSuccess)

export const getGetProductsUrl = (params?: GetProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/products?${stringifiedParams}` : `http://localhost:3000/products`
}

/**
 * Retrieve all Products with optional filtering
 * @summary Get all Products
 */
export const getProducts = async (params?: GetProductsParams, options?: RequestInit): Promise<getProductsResponse> => {

  const res = await fetch(getGetProductsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProductsResponse
}





export const getGetProductsQueryKey = (params?: GetProductsParams,) => {
    return [
    `http://localhost:3000/products`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) => getProducts(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = unknown


export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params: undefined |  GetProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all Products
 */

export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = unknown>(
 params?: GetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postProductsResponse201 = {
  data: Products
  status: 201
}

export type postProductsResponseSuccess = (postProductsResponse201) & {
  headers: Headers;
};
;

export type postProductsResponse = (postProductsResponseSuccess)

export const getPostProductsUrl = () => {




  return `http://localhost:3000/products`
}

/**
 * @summary Create product
 */
export const postProducts = async (createProduct: CreateProduct, options?: RequestInit): Promise<postProductsResponse> => {

  const res = await fetch(getPostProductsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProduct)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postProductsResponse
}




export const getPostProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: CreateProduct}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: CreateProduct}, TContext> => {

const mutationKey = ['postProducts'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProducts>>, {data: CreateProduct}> = (props) => {
          const {data} = props ?? {};

          return  postProducts(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postProducts>>>
    export type PostProductsMutationBody = CreateProduct
    export type PostProductsMutationError = unknown

    /**
 * @summary Create product
 */
export const usePostProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProducts>>, TError,{data: CreateProduct}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProducts>>,
        TError,
        {data: CreateProduct},
        TContext
      > => {
      return useMutation(getPostProductsMutationOptions(options), queryClient);
    }
    export type getProductsProductIdResponse200 = {
  data: Products
  status: 200
}

export type getProductsProductIdResponseSuccess = (getProductsProductIdResponse200) & {
  headers: Headers;
};
;

export type getProductsProductIdResponse = (getProductsProductIdResponseSuccess)

export const getGetProductsProductIdUrl = (productId: string,) => {




  return `http://localhost:3000/products/${productId}`
}

/**
 * @summary Get product by ID
 */
export const getProductsProductId = async (productId: string, options?: RequestInit): Promise<getProductsProductIdResponse> => {

  const res = await fetch(getGetProductsProductIdUrl(productId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProductsProductIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProductsProductIdResponse
}





export const getGetProductsProductIdQueryKey = (productId: string,) => {
    return [
    `http://localhost:3000/products/${productId}`
    ] as const;
    }


export const getGetProductsProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsProductIdQueryKey(productId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductsProductId>>> = ({ signal }) => getProductsProductId(productId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: productId !== null && productId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductsProductId>>>
export type GetProductsProductIdQueryError = unknown


export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsProductId>>,
          TError,
          Awaited<ReturnType<typeof getProductsProductId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductsProductId>>,
          TError,
          Awaited<ReturnType<typeof getProductsProductId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get product by ID
 */

export function useGetProductsProductId<TData = Awaited<ReturnType<typeof getProductsProductId>>, TError = unknown>(
 productId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductsProductId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsProductIdQueryOptions(productId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchProductsProductIdResponse200 = {
  data: Products
  status: 200
}

export type patchProductsProductIdResponseSuccess = (patchProductsProductIdResponse200) & {
  headers: Headers;
};
;

export type patchProductsProductIdResponse = (patchProductsProductIdResponseSuccess)

export const getPatchProductsProductIdUrl = (productId: string,) => {




  return `http://localhost:3000/products/${productId}`
}

/**
 * @summary Update product
 */
export const patchProductsProductId = async (productId: string,
    patchProduct: PatchProduct, options?: RequestInit): Promise<patchProductsProductIdResponse> => {

  const res = await fetch(getPatchProductsProductIdUrl(productId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchProduct)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchProductsProductIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchProductsProductIdResponse
}




export const getPatchProductsProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchProductsProductId>>, TError,{productId: string;data: PatchProduct}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchProductsProductId>>, TError,{productId: string;data: PatchProduct}, TContext> => {

const mutationKey = ['patchProductsProductId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchProductsProductId>>, {productId: string;data: PatchProduct}> = (props) => {
          const {productId,data} = props ?? {};

          return  patchProductsProductId(productId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchProductsProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchProductsProductId>>>
    export type PatchProductsProductIdMutationBody = PatchProduct
    export type PatchProductsProductIdMutationError = unknown

    /**
 * @summary Update product
 */
export const usePatchProductsProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchProductsProductId>>, TError,{productId: string;data: PatchProduct}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchProductsProductId>>,
        TError,
        {productId: string;data: PatchProduct},
        TContext
      > => {
      return useMutation(getPatchProductsProductIdMutationOptions(options), queryClient);
    }
    export type deleteProductsProductIdResponse204 = {
  data: void
  status: 204
}

export type deleteProductsProductIdResponseSuccess = (deleteProductsProductIdResponse204) & {
  headers: Headers;
};
;

export type deleteProductsProductIdResponse = (deleteProductsProductIdResponseSuccess)

export const getDeleteProductsProductIdUrl = (productId: string,) => {




  return `http://localhost:3000/products/${productId}`
}

/**
 * @summary Delete product
 */
export const deleteProductsProductId = async (productId: string, options?: RequestInit): Promise<deleteProductsProductIdResponse> => {

  const res = await fetch(getDeleteProductsProductIdUrl(productId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteProductsProductIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteProductsProductIdResponse
}




export const getDeleteProductsProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductsProductId>>, TError,{productId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProductsProductId>>, TError,{productId: string}, TContext> => {

const mutationKey = ['deleteProductsProductId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProductsProductId>>, {productId: string}> = (props) => {
          const {productId} = props ?? {};

          return  deleteProductsProductId(productId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductsProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProductsProductId>>>

    export type DeleteProductsProductIdMutationError = unknown

    /**
 * @summary Delete product
 */
export const useDeleteProductsProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProductsProductId>>, TError,{productId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProductsProductId>>,
        TError,
        {productId: string},
        TContext
      > => {
      return useMutation(getDeleteProductsProductIdMutationOptions(options), queryClient);
    }
    export type getUserProductsResponse200 = {
  data: GetUserProducts200
  status: 200
}

export type getUserProductsResponseSuccess = (getUserProductsResponse200) & {
  headers: Headers;
};
;

export type getUserProductsResponse = (getUserProductsResponseSuccess)

export const getGetUserProductsUrl = (params?: GetUserProductsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/user-products?${stringifiedParams}` : `http://localhost:3000/user-products`
}

/**
 * Retrieve user Products with optional filtering
 * @summary Get all user Products
 */
export const getUserProducts = async (params?: GetUserProductsParams, options?: RequestInit): Promise<getUserProductsResponse> => {

  const res = await fetch(getGetUserProductsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserProductsResponse
}





export const getGetUserProductsQueryKey = (params?: GetUserProductsParams,) => {
    return [
    `http://localhost:3000/user-products`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUserProductsQueryOptions = <TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProductsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProducts>>> = ({ signal }) => getUserProducts(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProducts>>>
export type GetUserProductsQueryError = unknown


export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params: undefined |  GetUserProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProducts>>,
          TError,
          Awaited<ReturnType<typeof getUserProducts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProducts>>,
          TError,
          Awaited<ReturnType<typeof getUserProducts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all user Products
 */

export function useGetUserProducts<TData = Awaited<ReturnType<typeof getUserProducts>>, TError = unknown>(
 params?: GetUserProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProducts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postUserProductsResponse201 = {
  data: UserProducts
  status: 201
}

export type postUserProductsResponseSuccess = (postUserProductsResponse201) & {
  headers: Headers;
};
;

export type postUserProductsResponse = (postUserProductsResponseSuccess)

export const getPostUserProductsUrl = () => {




  return `http://localhost:3000/user-products`
}

/**
 * @summary Create user product
 */
export const postUserProducts = async (createUserProduct: CreateUserProduct, options?: RequestInit): Promise<postUserProductsResponse> => {

  const res = await fetch(getPostUserProductsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserProduct)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postUserProductsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postUserProductsResponse
}




export const getPostUserProductsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUserProducts>>, TError,{data: CreateUserProduct}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postUserProducts>>, TError,{data: CreateUserProduct}, TContext> => {

const mutationKey = ['postUserProducts'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUserProducts>>, {data: CreateUserProduct}> = (props) => {
          const {data} = props ?? {};

          return  postUserProducts(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUserProductsMutationResult = NonNullable<Awaited<ReturnType<typeof postUserProducts>>>
    export type PostUserProductsMutationBody = CreateUserProduct
    export type PostUserProductsMutationError = unknown

    /**
 * @summary Create user product
 */
export const usePostUserProducts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUserProducts>>, TError,{data: CreateUserProduct}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUserProducts>>,
        TError,
        {data: CreateUserProduct},
        TContext
      > => {
      return useMutation(getPostUserProductsMutationOptions(options), queryClient);
    }
    export type getUserProductsUserProductIdResponse200 = {
  data: UserProducts
  status: 200
}

export type getUserProductsUserProductIdResponseSuccess = (getUserProductsUserProductIdResponse200) & {
  headers: Headers;
};
;

export type getUserProductsUserProductIdResponse = (getUserProductsUserProductIdResponseSuccess)

export const getGetUserProductsUserProductIdUrl = (userProductId: string,) => {




  return `http://localhost:3000/user-products/${userProductId}`
}

/**
 * @summary Get user product by ID
 */
export const getUserProductsUserProductId = async (userProductId: string, options?: RequestInit): Promise<getUserProductsUserProductIdResponse> => {

  const res = await fetch(getGetUserProductsUserProductIdUrl(userProductId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserProductsUserProductIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserProductsUserProductIdResponse
}





export const getGetUserProductsUserProductIdQueryKey = (userProductId: string,) => {
    return [
    `http://localhost:3000/user-products/${userProductId}`
    ] as const;
    }


export const getGetUserProductsUserProductIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProductsUserProductIdQueryKey(userProductId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProductsUserProductId>>> = ({ signal }) => getUserProductsUserProductId(userProductId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: userProductId !== null && userProductId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProductsUserProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProductsUserProductId>>>
export type GetUserProductsUserProductIdQueryError = unknown


export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProductsUserProductId>>,
          TError,
          Awaited<ReturnType<typeof getUserProductsUserProductId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProductsUserProductId>>,
          TError,
          Awaited<ReturnType<typeof getUserProductsUserProductId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user product by ID
 */

export function useGetUserProductsUserProductId<TData = Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError = unknown>(
 userProductId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProductsUserProductId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProductsUserProductIdQueryOptions(userProductId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchUserProductsUserProductIdResponse200 = {
  data: UserProducts
  status: 200
}

export type patchUserProductsUserProductIdResponseSuccess = (patchUserProductsUserProductIdResponse200) & {
  headers: Headers;
};
;

export type patchUserProductsUserProductIdResponse = (patchUserProductsUserProductIdResponseSuccess)

export const getPatchUserProductsUserProductIdUrl = (userProductId: string,) => {




  return `http://localhost:3000/user-products/${userProductId}`
}

/**
 * @summary Update user product
 */
export const patchUserProductsUserProductId = async (userProductId: string,
    patchUserProduct: PatchUserProduct, options?: RequestInit): Promise<patchUserProductsUserProductIdResponse> => {

  const res = await fetch(getPatchUserProductsUserProductIdUrl(userProductId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchUserProduct)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchUserProductsUserProductIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchUserProductsUserProductIdResponse
}




export const getPatchUserProductsUserProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, TError,{userProductId: string;data: PatchUserProduct}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, TError,{userProductId: string;data: PatchUserProduct}, TContext> => {

const mutationKey = ['patchUserProductsUserProductId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, {userProductId: string;data: PatchUserProduct}> = (props) => {
          const {userProductId,data} = props ?? {};

          return  patchUserProductsUserProductId(userProductId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchUserProductsUserProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchUserProductsUserProductId>>>
    export type PatchUserProductsUserProductIdMutationBody = PatchUserProduct
    export type PatchUserProductsUserProductIdMutationError = unknown

    /**
 * @summary Update user product
 */
export const usePatchUserProductsUserProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUserProductsUserProductId>>, TError,{userProductId: string;data: PatchUserProduct}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUserProductsUserProductId>>,
        TError,
        {userProductId: string;data: PatchUserProduct},
        TContext
      > => {
      return useMutation(getPatchUserProductsUserProductIdMutationOptions(options), queryClient);
    }
    export type deleteUserProductsUserProductIdResponse204 = {
  data: void
  status: 204
}

export type deleteUserProductsUserProductIdResponseSuccess = (deleteUserProductsUserProductIdResponse204) & {
  headers: Headers;
};
;

export type deleteUserProductsUserProductIdResponse = (deleteUserProductsUserProductIdResponseSuccess)

export const getDeleteUserProductsUserProductIdUrl = (userProductId: string,) => {




  return `http://localhost:3000/user-products/${userProductId}`
}

/**
 * @summary Delete user product
 */
export const deleteUserProductsUserProductId = async (userProductId: string, options?: RequestInit): Promise<deleteUserProductsUserProductIdResponse> => {

  const res = await fetch(getDeleteUserProductsUserProductIdUrl(userProductId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserProductsUserProductIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteUserProductsUserProductIdResponse
}




export const getDeleteUserProductsUserProductIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, TError,{userProductId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, TError,{userProductId: string}, TContext> => {

const mutationKey = ['deleteUserProductsUserProductId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, {userProductId: string}> = (props) => {
          const {userProductId} = props ?? {};

          return  deleteUserProductsUserProductId(userProductId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserProductsUserProductIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>>

    export type DeleteUserProductsUserProductIdMutationError = unknown

    /**
 * @summary Delete user product
 */
export const useDeleteUserProductsUserProductId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserProductsUserProductId>>, TError,{userProductId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserProductsUserProductId>>,
        TError,
        {userProductId: string},
        TContext
      > => {
      return useMutation(getDeleteUserProductsUserProductIdMutationOptions(options), queryClient);
    }
