/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ComposeServiceOrderRequest,
  ComposeServiceOrderResponse,
  CreateServiceOrder,
  GetServiceOrderComposerSearchParams,
  GetServiceOrders200,
  GetServiceOrdersParams,
  PatchServiceOrder,
  PostServiceOrderComposerSubmit400,
  PostServiceOrderComposerSubmit404,
  PostServiceOrderComposerSubmit409,
  ServiceOrderComposerSearchResponse,
  ServiceOrders
} from '../model';





export type getServiceOrdersResponse200 = {
  data: GetServiceOrders200
  status: 200
}

export type getServiceOrdersResponseSuccess = (getServiceOrdersResponse200) & {
  headers: Headers;
};
;

export type getServiceOrdersResponse = (getServiceOrdersResponseSuccess)

export const getGetServiceOrdersUrl = (params?: GetServiceOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/service-orders?${stringifiedParams}` : `http://localhost:3000/service-orders`
}

/**
 * Retrieve all service orders with optional filtering
 * @summary Get all service orders
 */
export const getServiceOrders = async (params?: GetServiceOrdersParams, options?: RequestInit): Promise<getServiceOrdersResponse> => {

  const res = await fetch(getGetServiceOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getServiceOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getServiceOrdersResponse
}





export const getGetServiceOrdersQueryKey = (params?: GetServiceOrdersParams,) => {
    return [
    `http://localhost:3000/service-orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetServiceOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOrders>>> = ({ signal }) => getServiceOrders(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOrders>>>
export type GetServiceOrdersQueryError = unknown


export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params: undefined |  GetServiceOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrders>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrders>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrders>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrders>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all service orders
 */

export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postServiceOrdersResponse201 = {
  data: ServiceOrders
  status: 201
}

export type postServiceOrdersResponseSuccess = (postServiceOrdersResponse201) & {
  headers: Headers;
};
;

export type postServiceOrdersResponse = (postServiceOrdersResponseSuccess)

export const getPostServiceOrdersUrl = () => {




  return `http://localhost:3000/service-orders`
}

/**
 * Create a new service order
 * @summary Create service order
 */
export const postServiceOrders = async (createServiceOrder: CreateServiceOrder, options?: RequestInit): Promise<postServiceOrdersResponse> => {

  const res = await fetch(getPostServiceOrdersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createServiceOrder)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postServiceOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postServiceOrdersResponse
}




export const getPostServiceOrdersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrders>>, TError,{data: CreateServiceOrder}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceOrders>>, TError,{data: CreateServiceOrder}, TContext> => {

const mutationKey = ['postServiceOrders'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceOrders>>, {data: CreateServiceOrder}> = (props) => {
          const {data} = props ?? {};

          return  postServiceOrders(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceOrdersMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceOrders>>>
    export type PostServiceOrdersMutationBody = CreateServiceOrder
    export type PostServiceOrdersMutationError = unknown

    /**
 * @summary Create service order
 */
export const usePostServiceOrders = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrders>>, TError,{data: CreateServiceOrder}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postServiceOrders>>,
        TError,
        {data: CreateServiceOrder},
        TContext
      > => {
      return useMutation(getPostServiceOrdersMutationOptions(options), queryClient);
    }
    export type getServiceOrdersServiceOrderIdResponse200 = {
  data: ServiceOrders
  status: 200
}

export type getServiceOrdersServiceOrderIdResponse404 = {
  data: void
  status: 404
}

export type getServiceOrdersServiceOrderIdResponseSuccess = (getServiceOrdersServiceOrderIdResponse200) & {
  headers: Headers;
};
export type getServiceOrdersServiceOrderIdResponseError = (getServiceOrdersServiceOrderIdResponse404) & {
  headers: Headers;
};

export type getServiceOrdersServiceOrderIdResponse = (getServiceOrdersServiceOrderIdResponseSuccess | getServiceOrdersServiceOrderIdResponseError)

export const getGetServiceOrdersServiceOrderIdUrl = (serviceOrderId: string,) => {




  return `http://localhost:3000/service-orders/${serviceOrderId}`
}

/**
 * @summary Get service order by ID
 */
export const getServiceOrdersServiceOrderId = async (serviceOrderId: string, options?: RequestInit): Promise<getServiceOrdersServiceOrderIdResponse> => {

  const res = await fetch(getGetServiceOrdersServiceOrderIdUrl(serviceOrderId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getServiceOrdersServiceOrderIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getServiceOrdersServiceOrderIdResponse
}





export const getGetServiceOrdersServiceOrderIdQueryKey = (serviceOrderId: string,) => {
    return [
    `http://localhost:3000/service-orders/${serviceOrderId}`
    ] as const;
    }


export const getGetServiceOrdersServiceOrderIdQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOrdersServiceOrderIdQueryKey(serviceOrderId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>> = ({ signal }) => getServiceOrdersServiceOrderId(serviceOrderId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: serviceOrderId !== null && serviceOrderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceOrdersServiceOrderIdQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>>
export type GetServiceOrdersServiceOrderIdQueryError = void


export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get service order by ID
 */

export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceOrdersServiceOrderIdQueryOptions(serviceOrderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchServiceOrdersServiceOrderIdResponse200 = {
  data: ServiceOrders
  status: 200
}

export type patchServiceOrdersServiceOrderIdResponse404 = {
  data: void
  status: 404
}

export type patchServiceOrdersServiceOrderIdResponseSuccess = (patchServiceOrdersServiceOrderIdResponse200) & {
  headers: Headers;
};
export type patchServiceOrdersServiceOrderIdResponseError = (patchServiceOrdersServiceOrderIdResponse404) & {
  headers: Headers;
};

export type patchServiceOrdersServiceOrderIdResponse = (patchServiceOrdersServiceOrderIdResponseSuccess | patchServiceOrdersServiceOrderIdResponseError)

export const getPatchServiceOrdersServiceOrderIdUrl = (serviceOrderId: string,) => {




  return `http://localhost:3000/service-orders/${serviceOrderId}`
}

/**
 * @summary Update service order
 */
export const patchServiceOrdersServiceOrderId = async (serviceOrderId: string,
    patchServiceOrder: PatchServiceOrder, options?: RequestInit): Promise<patchServiceOrdersServiceOrderIdResponse> => {

  const res = await fetch(getPatchServiceOrdersServiceOrderIdUrl(serviceOrderId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchServiceOrder)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchServiceOrdersServiceOrderIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchServiceOrdersServiceOrderIdResponse
}




export const getPatchServiceOrdersServiceOrderIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string;data: PatchServiceOrder}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string;data: PatchServiceOrder}, TContext> => {

const mutationKey = ['patchServiceOrdersServiceOrderId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, {serviceOrderId: string;data: PatchServiceOrder}> = (props) => {
          const {serviceOrderId,data} = props ?? {};

          return  patchServiceOrdersServiceOrderId(serviceOrderId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchServiceOrdersServiceOrderIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>>
    export type PatchServiceOrdersServiceOrderIdMutationBody = PatchServiceOrder
    export type PatchServiceOrdersServiceOrderIdMutationError = void

    /**
 * @summary Update service order
 */
export const usePatchServiceOrdersServiceOrderId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string;data: PatchServiceOrder}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>,
        TError,
        {serviceOrderId: string;data: PatchServiceOrder},
        TContext
      > => {
      return useMutation(getPatchServiceOrdersServiceOrderIdMutationOptions(options), queryClient);
    }
    export type deleteServiceOrdersServiceOrderIdResponse204 = {
  data: void
  status: 204
}

export type deleteServiceOrdersServiceOrderIdResponseSuccess = (deleteServiceOrdersServiceOrderIdResponse204) & {
  headers: Headers;
};
;

export type deleteServiceOrdersServiceOrderIdResponse = (deleteServiceOrdersServiceOrderIdResponseSuccess)

export const getDeleteServiceOrdersServiceOrderIdUrl = (serviceOrderId: string,) => {




  return `http://localhost:3000/service-orders/${serviceOrderId}`
}

/**
 * @summary Delete service order
 */
export const deleteServiceOrdersServiceOrderId = async (serviceOrderId: string, options?: RequestInit): Promise<deleteServiceOrdersServiceOrderIdResponse> => {

  const res = await fetch(getDeleteServiceOrdersServiceOrderIdUrl(serviceOrderId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteServiceOrdersServiceOrderIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteServiceOrdersServiceOrderIdResponse
}




export const getDeleteServiceOrdersServiceOrderIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string}, TContext> => {

const mutationKey = ['deleteServiceOrdersServiceOrderId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, {serviceOrderId: string}> = (props) => {
          const {serviceOrderId} = props ?? {};

          return  deleteServiceOrdersServiceOrderId(serviceOrderId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceOrdersServiceOrderIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>>

    export type DeleteServiceOrdersServiceOrderIdMutationError = unknown

    /**
 * @summary Delete service order
 */
export const useDeleteServiceOrdersServiceOrderId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>,
        TError,
        {serviceOrderId: string},
        TContext
      > => {
      return useMutation(getDeleteServiceOrdersServiceOrderIdMutationOptions(options), queryClient);
    }
    export type getServiceOrderComposerSearchResponse200 = {
  data: ServiceOrderComposerSearchResponse
  status: 200
}

export type getServiceOrderComposerSearchResponseSuccess = (getServiceOrderComposerSearchResponse200) & {
  headers: Headers;
};
;

export type getServiceOrderComposerSearchResponse = (getServiceOrderComposerSearchResponseSuccess)

export const getGetServiceOrderComposerSearchUrl = (params?: GetServiceOrderComposerSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/service-order-composer/search?${stringifiedParams}` : `http://localhost:3000/service-order-composer/search`
}

/**
 * Retrieve relationship-aware customer, product, and device contexts for service order creation.
 * @summary Search service order composition contexts
 */
export const getServiceOrderComposerSearch = async (params?: GetServiceOrderComposerSearchParams, options?: RequestInit): Promise<getServiceOrderComposerSearchResponse> => {

  const res = await fetch(getGetServiceOrderComposerSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getServiceOrderComposerSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getServiceOrderComposerSearchResponse
}





export const getGetServiceOrderComposerSearchQueryKey = (params?: GetServiceOrderComposerSearchParams,) => {
    return [
    `http://localhost:3000/service-order-composer/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetServiceOrderComposerSearchQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOrderComposerSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>> = ({ signal }) => getServiceOrderComposerSearch(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceOrderComposerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>>
export type GetServiceOrderComposerSearchQueryError = unknown


export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params: undefined |  GetServiceOrderComposerSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search service order composition contexts
 */

export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceOrderComposerSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postServiceOrderComposerSubmitResponse201 = {
  data: ComposeServiceOrderResponse
  status: 201
}

export type postServiceOrderComposerSubmitResponse400 = {
  data: PostServiceOrderComposerSubmit400
  status: 400
}

export type postServiceOrderComposerSubmitResponse404 = {
  data: PostServiceOrderComposerSubmit404
  status: 404
}

export type postServiceOrderComposerSubmitResponse409 = {
  data: PostServiceOrderComposerSubmit409
  status: 409
}

export type postServiceOrderComposerSubmitResponseSuccess = (postServiceOrderComposerSubmitResponse201) & {
  headers: Headers;
};
export type postServiceOrderComposerSubmitResponseError = (postServiceOrderComposerSubmitResponse400 | postServiceOrderComposerSubmitResponse404 | postServiceOrderComposerSubmitResponse409) & {
  headers: Headers;
};

export type postServiceOrderComposerSubmitResponse = (postServiceOrderComposerSubmitResponseSuccess | postServiceOrderComposerSubmitResponseError)

export const getPostServiceOrderComposerSubmitUrl = () => {




  return `http://localhost:3000/service-order-composer/submit`
}

/**
 * Create or reuse existing related entities and persist a new service order in a single transaction.
 * @summary Submit composed service order workflow
 */
export const postServiceOrderComposerSubmit = async (composeServiceOrderRequest: ComposeServiceOrderRequest, options?: RequestInit): Promise<postServiceOrderComposerSubmitResponse> => {

  const res = await fetch(getPostServiceOrderComposerSubmitUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(composeServiceOrderRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postServiceOrderComposerSubmitResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postServiceOrderComposerSubmitResponse
}




export const getPostServiceOrderComposerSubmitMutationOptions = <TError = PostServiceOrderComposerSubmit400 | PostServiceOrderComposerSubmit404 | PostServiceOrderComposerSubmit409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, TError,{data: ComposeServiceOrderRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, TError,{data: ComposeServiceOrderRequest}, TContext> => {

const mutationKey = ['postServiceOrderComposerSubmit'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, {data: ComposeServiceOrderRequest}> = (props) => {
          const {data} = props ?? {};

          return  postServiceOrderComposerSubmit(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceOrderComposerSubmitMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>>
    export type PostServiceOrderComposerSubmitMutationBody = ComposeServiceOrderRequest
    export type PostServiceOrderComposerSubmitMutationError = PostServiceOrderComposerSubmit400 | PostServiceOrderComposerSubmit404 | PostServiceOrderComposerSubmit409

    /**
 * @summary Submit composed service order workflow
 */
export const usePostServiceOrderComposerSubmit = <TError = PostServiceOrderComposerSubmit400 | PostServiceOrderComposerSubmit404 | PostServiceOrderComposerSubmit409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, TError,{data: ComposeServiceOrderRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>,
        TError,
        {data: ComposeServiceOrderRequest},
        TContext
      > => {
      return useMutation(getPostServiceOrderComposerSubmitMutationOptions(options), queryClient);
    }
