/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ComposeServiceOrderRequest,
  ComposeServiceOrderResponse,
  CreateServiceOrder,
  GetServiceOrderComposerSearchParams,
  GetServiceOrders200,
  GetServiceOrdersParams,
  PatchServiceOrder,
  PostServiceOrderComposerSubmit400,
  PostServiceOrderComposerSubmit404,
  PostServiceOrderComposerSubmit409,
  ServiceOrderComposerSearchResponse,
  ServiceOrders
} from '../model';

import { customInstance } from '../../lib/api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all service orders with optional filtering
 * @summary Get all service orders
 */
export const getServiceOrders = (
    params?: GetServiceOrdersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<GetServiceOrders200>(
      {url: `/service-orders`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetServiceOrdersQueryKey = (params?: GetServiceOrdersParams,) => {
    return [
    `/service-orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetServiceOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOrders>>> = ({ signal }) => getServiceOrders(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOrders>>>
export type GetServiceOrdersQueryError = unknown


export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params: undefined |  GetServiceOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrders>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrders>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrders>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all service orders
 */

export function useGetServiceOrders<TData = Awaited<ReturnType<typeof getServiceOrders>>, TError = unknown>(
 params?: GetServiceOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create a new service order
 * @summary Create service order
 */
export const postServiceOrders = (
    createServiceOrder: CreateServiceOrder,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceOrders>(
      {url: `/service-orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createServiceOrder, signal
    },
      options);
    }



export const getPostServiceOrdersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrders>>, TError,{data: CreateServiceOrder}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceOrders>>, TError,{data: CreateServiceOrder}, TContext> => {

const mutationKey = ['postServiceOrders'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceOrders>>, {data: CreateServiceOrder}> = (props) => {
          const {data} = props ?? {};

          return  postServiceOrders(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceOrdersMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceOrders>>>
    export type PostServiceOrdersMutationBody = CreateServiceOrder
    export type PostServiceOrdersMutationError = unknown

    /**
 * @summary Create service order
 */
export const usePostServiceOrders = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrders>>, TError,{data: CreateServiceOrder}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postServiceOrders>>,
        TError,
        {data: CreateServiceOrder},
        TContext
      > => {
      return useMutation(getPostServiceOrdersMutationOptions(options), queryClient);
    }
    /**
 * @summary Get service order by ID
 */
export const getServiceOrdersServiceOrderId = (
    serviceOrderId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceOrders>(
      {url: `/service-orders/${serviceOrderId}`, method: 'GET', signal
    },
      options);
    }




export const getGetServiceOrdersServiceOrderIdQueryKey = (serviceOrderId: string,) => {
    return [
    `/service-orders/${serviceOrderId}`
    ] as const;
    }


export const getGetServiceOrdersServiceOrderIdQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOrdersServiceOrderIdQueryKey(serviceOrderId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>> = ({ signal }) => getServiceOrdersServiceOrderId(serviceOrderId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: serviceOrderId !== null && serviceOrderId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceOrdersServiceOrderIdQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>>
export type GetServiceOrdersServiceOrderIdQueryError = void


export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get service order by ID
 */

export function useGetServiceOrdersServiceOrderId<TData = Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError = void>(
 serviceOrderId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrdersServiceOrderId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceOrdersServiceOrderIdQueryOptions(serviceOrderId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update service order
 */
export const patchServiceOrdersServiceOrderId = (
    serviceOrderId: string,
    patchServiceOrder: PatchServiceOrder,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceOrders>(
      {url: `/service-orders/${serviceOrderId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchServiceOrder, signal
    },
      options);
    }



export const getPatchServiceOrdersServiceOrderIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string;data: PatchServiceOrder}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string;data: PatchServiceOrder}, TContext> => {

const mutationKey = ['patchServiceOrdersServiceOrderId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, {serviceOrderId: string;data: PatchServiceOrder}> = (props) => {
          const {serviceOrderId,data} = props ?? {};

          return  patchServiceOrdersServiceOrderId(serviceOrderId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchServiceOrdersServiceOrderIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>>
    export type PatchServiceOrdersServiceOrderIdMutationBody = PatchServiceOrder
    export type PatchServiceOrdersServiceOrderIdMutationError = void

    /**
 * @summary Update service order
 */
export const usePatchServiceOrdersServiceOrderId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string;data: PatchServiceOrder}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchServiceOrdersServiceOrderId>>,
        TError,
        {serviceOrderId: string;data: PatchServiceOrder},
        TContext
      > => {
      return useMutation(getPatchServiceOrdersServiceOrderIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete service order
 */
export const deleteServiceOrdersServiceOrderId = (
    serviceOrderId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/service-orders/${serviceOrderId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteServiceOrdersServiceOrderIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string}, TContext> => {

const mutationKey = ['deleteServiceOrdersServiceOrderId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, {serviceOrderId: string}> = (props) => {
          const {serviceOrderId} = props ?? {};

          return  deleteServiceOrdersServiceOrderId(serviceOrderId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceOrdersServiceOrderIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>>

    export type DeleteServiceOrdersServiceOrderIdMutationError = unknown

    /**
 * @summary Delete service order
 */
export const useDeleteServiceOrdersServiceOrderId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>, TError,{serviceOrderId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteServiceOrdersServiceOrderId>>,
        TError,
        {serviceOrderId: string},
        TContext
      > => {
      return useMutation(getDeleteServiceOrdersServiceOrderIdMutationOptions(options), queryClient);
    }
    /**
 * Retrieve relationship-aware customer, product, and device contexts for service order creation.
 * @summary Search service order composition contexts
 */
export const getServiceOrderComposerSearch = (
    params?: GetServiceOrderComposerSearchParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ServiceOrderComposerSearchResponse>(
      {url: `/service-order-composer/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetServiceOrderComposerSearchQueryKey = (params?: GetServiceOrderComposerSearchParams,) => {
    return [
    `/service-order-composer/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetServiceOrderComposerSearchQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOrderComposerSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>> = ({ signal }) => getServiceOrderComposerSearch(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceOrderComposerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>>
export type GetServiceOrderComposerSearchQueryError = unknown


export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params: undefined |  GetServiceOrderComposerSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>,
          TError,
          Awaited<ReturnType<typeof getServiceOrderComposerSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search service order composition contexts
 */

export function useGetServiceOrderComposerSearch<TData = Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError = unknown>(
 params?: GetServiceOrderComposerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceOrderComposerSearch>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetServiceOrderComposerSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Create or reuse existing related entities and persist a new service order in a single transaction.
 * @summary Submit composed service order workflow
 */
export const postServiceOrderComposerSubmit = (
    composeServiceOrderRequest: ComposeServiceOrderRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ComposeServiceOrderResponse>(
      {url: `/service-order-composer/submit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: composeServiceOrderRequest, signal
    },
      options);
    }



export const getPostServiceOrderComposerSubmitMutationOptions = <TError = PostServiceOrderComposerSubmit400 | PostServiceOrderComposerSubmit404 | PostServiceOrderComposerSubmit409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, TError,{data: ComposeServiceOrderRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, TError,{data: ComposeServiceOrderRequest}, TContext> => {

const mutationKey = ['postServiceOrderComposerSubmit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, {data: ComposeServiceOrderRequest}> = (props) => {
          const {data} = props ?? {};

          return  postServiceOrderComposerSubmit(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceOrderComposerSubmitMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>>
    export type PostServiceOrderComposerSubmitMutationBody = ComposeServiceOrderRequest
    export type PostServiceOrderComposerSubmitMutationError = PostServiceOrderComposerSubmit400 | PostServiceOrderComposerSubmit404 | PostServiceOrderComposerSubmit409

    /**
 * @summary Submit composed service order workflow
 */
export const usePostServiceOrderComposerSubmit = <TError = PostServiceOrderComposerSubmit400 | PostServiceOrderComposerSubmit404 | PostServiceOrderComposerSubmit409,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>, TError,{data: ComposeServiceOrderRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postServiceOrderComposerSubmit>>,
        TError,
        {data: ComposeServiceOrderRequest},
        TContext
      > => {
      return useMutation(getPostServiceOrderComposerSubmitMutationOptions(options), queryClient);
    }
