/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Brands,
  CreateBrand,
  CreateProductType,
  CreateRole,
  CreateStatus,
  PatchBrand,
  PatchProductType,
  PatchRole,
  PatchStatus,
  ProductTypes,
  Roles,
  Statuses
} from '../model';





export type getReferencesRolesResponse200 = {
  data: Roles[]
  status: 200
}

export type getReferencesRolesResponseSuccess = (getReferencesRolesResponse200) & {
  headers: Headers;
};
;

export type getReferencesRolesResponse = (getReferencesRolesResponseSuccess)

export const getGetReferencesRolesUrl = () => {




  return `http://localhost:3000/references/roles`
}

/**
 * @summary Get all roles
 */
export const getReferencesRoles = async ( options?: RequestInit): Promise<getReferencesRolesResponse> => {

  const res = await fetch(getGetReferencesRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReferencesRolesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReferencesRolesResponse
}





export const getGetReferencesRolesQueryKey = () => {
    return [
    `http://localhost:3000/references/roles`
    ] as const;
    }


export const getGetReferencesRolesQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesRoles>>> = ({ signal }) => getReferencesRoles({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesRoles>>>
export type GetReferencesRolesQueryError = unknown


export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesRoles>>,
          TError,
          Awaited<ReturnType<typeof getReferencesRoles>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesRoles>>,
          TError,
          Awaited<ReturnType<typeof getReferencesRoles>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all roles
 */

export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postReferencesRolesResponse201 = {
  data: Roles
  status: 201
}

export type postReferencesRolesResponseSuccess = (postReferencesRolesResponse201) & {
  headers: Headers;
};
;

export type postReferencesRolesResponse = (postReferencesRolesResponseSuccess)

export const getPostReferencesRolesUrl = () => {




  return `http://localhost:3000/references/roles`
}

/**
 * @summary Create role
 */
export const postReferencesRoles = async (createRole: CreateRole, options?: RequestInit): Promise<postReferencesRolesResponse> => {

  const res = await fetch(getPostReferencesRolesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRole)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postReferencesRolesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postReferencesRolesResponse
}




export const getPostReferencesRolesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesRoles>>, TError,{data: CreateRole}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesRoles>>, TError,{data: CreateRole}, TContext> => {

const mutationKey = ['postReferencesRoles'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesRoles>>, {data: CreateRole}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesRoles(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesRoles>>>
    export type PostReferencesRolesMutationBody = CreateRole
    export type PostReferencesRolesMutationError = unknown

    /**
 * @summary Create role
 */
export const usePostReferencesRoles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesRoles>>, TError,{data: CreateRole}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesRoles>>,
        TError,
        {data: CreateRole},
        TContext
      > => {
      return useMutation(getPostReferencesRolesMutationOptions(options), queryClient);
    }
    export type patchReferencesRolesRoleIdResponse200 = {
  data: Roles
  status: 200
}

export type patchReferencesRolesRoleIdResponseSuccess = (patchReferencesRolesRoleIdResponse200) & {
  headers: Headers;
};
;

export type patchReferencesRolesRoleIdResponse = (patchReferencesRolesRoleIdResponseSuccess)

export const getPatchReferencesRolesRoleIdUrl = (roleId: string,) => {




  return `http://localhost:3000/references/roles/${roleId}`
}

/**
 * @summary Update role
 */
export const patchReferencesRolesRoleId = async (roleId: string,
    patchRole: PatchRole, options?: RequestInit): Promise<patchReferencesRolesRoleIdResponse> => {

  const res = await fetch(getPatchReferencesRolesRoleIdUrl(roleId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchRole)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchReferencesRolesRoleIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchReferencesRolesRoleIdResponse
}




export const getPatchReferencesRolesRoleIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, TError,{roleId: string;data: PatchRole}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, TError,{roleId: string;data: PatchRole}, TContext> => {

const mutationKey = ['patchReferencesRolesRoleId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, {roleId: string;data: PatchRole}> = (props) => {
          const {roleId,data} = props ?? {};

          return  patchReferencesRolesRoleId(roleId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesRolesRoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>>
    export type PatchReferencesRolesRoleIdMutationBody = PatchRole
    export type PatchReferencesRolesRoleIdMutationError = unknown

    /**
 * @summary Update role
 */
export const usePatchReferencesRolesRoleId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, TError,{roleId: string;data: PatchRole}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesRolesRoleId>>,
        TError,
        {roleId: string;data: PatchRole},
        TContext
      > => {
      return useMutation(getPatchReferencesRolesRoleIdMutationOptions(options), queryClient);
    }
    export type deleteReferencesRolesRoleIdResponse204 = {
  data: void
  status: 204
}

export type deleteReferencesRolesRoleIdResponseSuccess = (deleteReferencesRolesRoleIdResponse204) & {
  headers: Headers;
};
;

export type deleteReferencesRolesRoleIdResponse = (deleteReferencesRolesRoleIdResponseSuccess)

export const getDeleteReferencesRolesRoleIdUrl = (roleId: string,) => {




  return `http://localhost:3000/references/roles/${roleId}`
}

/**
 * @summary Delete role
 */
export const deleteReferencesRolesRoleId = async (roleId: string, options?: RequestInit): Promise<deleteReferencesRolesRoleIdResponse> => {

  const res = await fetch(getDeleteReferencesRolesRoleIdUrl(roleId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteReferencesRolesRoleIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteReferencesRolesRoleIdResponse
}




export const getDeleteReferencesRolesRoleIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, TError,{roleId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, TError,{roleId: string}, TContext> => {

const mutationKey = ['deleteReferencesRolesRoleId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, {roleId: string}> = (props) => {
          const {roleId} = props ?? {};

          return  deleteReferencesRolesRoleId(roleId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesRolesRoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>>

    export type DeleteReferencesRolesRoleIdMutationError = unknown

    /**
 * @summary Delete role
 */
export const useDeleteReferencesRolesRoleId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, TError,{roleId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>,
        TError,
        {roleId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesRolesRoleIdMutationOptions(options), queryClient);
    }
    export type getReferencesBrandsResponse200 = {
  data: Brands[]
  status: 200
}

export type getReferencesBrandsResponseSuccess = (getReferencesBrandsResponse200) & {
  headers: Headers;
};
;

export type getReferencesBrandsResponse = (getReferencesBrandsResponseSuccess)

export const getGetReferencesBrandsUrl = () => {




  return `http://localhost:3000/references/brands`
}

/**
 * @summary Get all brands
 */
export const getReferencesBrands = async ( options?: RequestInit): Promise<getReferencesBrandsResponse> => {

  const res = await fetch(getGetReferencesBrandsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReferencesBrandsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReferencesBrandsResponse
}





export const getGetReferencesBrandsQueryKey = () => {
    return [
    `http://localhost:3000/references/brands`
    ] as const;
    }


export const getGetReferencesBrandsQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesBrandsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesBrands>>> = ({ signal }) => getReferencesBrands({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesBrandsQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesBrands>>>
export type GetReferencesBrandsQueryError = unknown


export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesBrands>>,
          TError,
          Awaited<ReturnType<typeof getReferencesBrands>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesBrands>>,
          TError,
          Awaited<ReturnType<typeof getReferencesBrands>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all brands
 */

export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesBrandsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postReferencesBrandsResponse201 = {
  data: Brands
  status: 201
}

export type postReferencesBrandsResponseSuccess = (postReferencesBrandsResponse201) & {
  headers: Headers;
};
;

export type postReferencesBrandsResponse = (postReferencesBrandsResponseSuccess)

export const getPostReferencesBrandsUrl = () => {




  return `http://localhost:3000/references/brands`
}

/**
 * @summary Create brand
 */
export const postReferencesBrands = async (createBrand: CreateBrand, options?: RequestInit): Promise<postReferencesBrandsResponse> => {

  const res = await fetch(getPostReferencesBrandsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBrand)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postReferencesBrandsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postReferencesBrandsResponse
}




export const getPostReferencesBrandsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesBrands>>, TError,{data: CreateBrand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesBrands>>, TError,{data: CreateBrand}, TContext> => {

const mutationKey = ['postReferencesBrands'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesBrands>>, {data: CreateBrand}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesBrands(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesBrandsMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesBrands>>>
    export type PostReferencesBrandsMutationBody = CreateBrand
    export type PostReferencesBrandsMutationError = unknown

    /**
 * @summary Create brand
 */
export const usePostReferencesBrands = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesBrands>>, TError,{data: CreateBrand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesBrands>>,
        TError,
        {data: CreateBrand},
        TContext
      > => {
      return useMutation(getPostReferencesBrandsMutationOptions(options), queryClient);
    }
    export type patchReferencesBrandsBrandIdResponse200 = {
  data: Brands
  status: 200
}

export type patchReferencesBrandsBrandIdResponseSuccess = (patchReferencesBrandsBrandIdResponse200) & {
  headers: Headers;
};
;

export type patchReferencesBrandsBrandIdResponse = (patchReferencesBrandsBrandIdResponseSuccess)

export const getPatchReferencesBrandsBrandIdUrl = (brandId: string,) => {




  return `http://localhost:3000/references/brands/${brandId}`
}

/**
 * @summary Update brand
 */
export const patchReferencesBrandsBrandId = async (brandId: string,
    patchBrand: PatchBrand, options?: RequestInit): Promise<patchReferencesBrandsBrandIdResponse> => {

  const res = await fetch(getPatchReferencesBrandsBrandIdUrl(brandId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchBrand)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchReferencesBrandsBrandIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchReferencesBrandsBrandIdResponse
}




export const getPatchReferencesBrandsBrandIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, TError,{brandId: string;data: PatchBrand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, TError,{brandId: string;data: PatchBrand}, TContext> => {

const mutationKey = ['patchReferencesBrandsBrandId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, {brandId: string;data: PatchBrand}> = (props) => {
          const {brandId,data} = props ?? {};

          return  patchReferencesBrandsBrandId(brandId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesBrandsBrandIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>>
    export type PatchReferencesBrandsBrandIdMutationBody = PatchBrand
    export type PatchReferencesBrandsBrandIdMutationError = unknown

    /**
 * @summary Update brand
 */
export const usePatchReferencesBrandsBrandId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, TError,{brandId: string;data: PatchBrand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>,
        TError,
        {brandId: string;data: PatchBrand},
        TContext
      > => {
      return useMutation(getPatchReferencesBrandsBrandIdMutationOptions(options), queryClient);
    }
    export type deleteReferencesBrandsBrandIdResponse204 = {
  data: void
  status: 204
}

export type deleteReferencesBrandsBrandIdResponseSuccess = (deleteReferencesBrandsBrandIdResponse204) & {
  headers: Headers;
};
;

export type deleteReferencesBrandsBrandIdResponse = (deleteReferencesBrandsBrandIdResponseSuccess)

export const getDeleteReferencesBrandsBrandIdUrl = (brandId: string,) => {




  return `http://localhost:3000/references/brands/${brandId}`
}

/**
 * @summary Delete brand
 */
export const deleteReferencesBrandsBrandId = async (brandId: string, options?: RequestInit): Promise<deleteReferencesBrandsBrandIdResponse> => {

  const res = await fetch(getDeleteReferencesBrandsBrandIdUrl(brandId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteReferencesBrandsBrandIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteReferencesBrandsBrandIdResponse
}




export const getDeleteReferencesBrandsBrandIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, TError,{brandId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, TError,{brandId: string}, TContext> => {

const mutationKey = ['deleteReferencesBrandsBrandId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, {brandId: string}> = (props) => {
          const {brandId} = props ?? {};

          return  deleteReferencesBrandsBrandId(brandId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesBrandsBrandIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>>

    export type DeleteReferencesBrandsBrandIdMutationError = unknown

    /**
 * @summary Delete brand
 */
export const useDeleteReferencesBrandsBrandId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, TError,{brandId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>,
        TError,
        {brandId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesBrandsBrandIdMutationOptions(options), queryClient);
    }
    export type getReferencesProductTypesResponse200 = {
  data: ProductTypes[]
  status: 200
}

export type getReferencesProductTypesResponseSuccess = (getReferencesProductTypesResponse200) & {
  headers: Headers;
};
;

export type getReferencesProductTypesResponse = (getReferencesProductTypesResponseSuccess)

export const getGetReferencesProductTypesUrl = () => {




  return `http://localhost:3000/references/product-types`
}

/**
 * @summary Get all product types
 */
export const getReferencesProductTypes = async ( options?: RequestInit): Promise<getReferencesProductTypesResponse> => {

  const res = await fetch(getGetReferencesProductTypesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReferencesProductTypesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReferencesProductTypesResponse
}





export const getGetReferencesProductTypesQueryKey = () => {
    return [
    `http://localhost:3000/references/product-types`
    ] as const;
    }


export const getGetReferencesProductTypesQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesProductTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesProductTypes>>> = ({ signal }) => getReferencesProductTypes({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesProductTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesProductTypes>>>
export type GetReferencesProductTypesQueryError = unknown


export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesProductTypes>>,
          TError,
          Awaited<ReturnType<typeof getReferencesProductTypes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesProductTypes>>,
          TError,
          Awaited<ReturnType<typeof getReferencesProductTypes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all product types
 */

export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesProductTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postReferencesProductTypesResponse201 = {
  data: ProductTypes
  status: 201
}

export type postReferencesProductTypesResponseSuccess = (postReferencesProductTypesResponse201) & {
  headers: Headers;
};
;

export type postReferencesProductTypesResponse = (postReferencesProductTypesResponseSuccess)

export const getPostReferencesProductTypesUrl = () => {




  return `http://localhost:3000/references/product-types`
}

/**
 * @summary Create product type
 */
export const postReferencesProductTypes = async (createProductType: CreateProductType, options?: RequestInit): Promise<postReferencesProductTypesResponse> => {

  const res = await fetch(getPostReferencesProductTypesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProductType)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postReferencesProductTypesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postReferencesProductTypesResponse
}




export const getPostReferencesProductTypesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesProductTypes>>, TError,{data: CreateProductType}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesProductTypes>>, TError,{data: CreateProductType}, TContext> => {

const mutationKey = ['postReferencesProductTypes'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesProductTypes>>, {data: CreateProductType}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesProductTypes(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesProductTypesMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesProductTypes>>>
    export type PostReferencesProductTypesMutationBody = CreateProductType
    export type PostReferencesProductTypesMutationError = unknown

    /**
 * @summary Create product type
 */
export const usePostReferencesProductTypes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesProductTypes>>, TError,{data: CreateProductType}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesProductTypes>>,
        TError,
        {data: CreateProductType},
        TContext
      > => {
      return useMutation(getPostReferencesProductTypesMutationOptions(options), queryClient);
    }
    export type patchReferencesProductTypesProductTypeIdResponse200 = {
  data: ProductTypes
  status: 200
}

export type patchReferencesProductTypesProductTypeIdResponseSuccess = (patchReferencesProductTypesProductTypeIdResponse200) & {
  headers: Headers;
};
;

export type patchReferencesProductTypesProductTypeIdResponse = (patchReferencesProductTypesProductTypeIdResponseSuccess)

export const getPatchReferencesProductTypesProductTypeIdUrl = (productTypeId: string,) => {




  return `http://localhost:3000/references/product-types/${productTypeId}`
}

/**
 * @summary Update product type
 */
export const patchReferencesProductTypesProductTypeId = async (productTypeId: string,
    patchProductType: PatchProductType, options?: RequestInit): Promise<patchReferencesProductTypesProductTypeIdResponse> => {

  const res = await fetch(getPatchReferencesProductTypesProductTypeIdUrl(productTypeId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchProductType)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchReferencesProductTypesProductTypeIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchReferencesProductTypesProductTypeIdResponse
}




export const getPatchReferencesProductTypesProductTypeIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, TError,{productTypeId: string;data: PatchProductType}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, TError,{productTypeId: string;data: PatchProductType}, TContext> => {

const mutationKey = ['patchReferencesProductTypesProductTypeId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, {productTypeId: string;data: PatchProductType}> = (props) => {
          const {productTypeId,data} = props ?? {};

          return  patchReferencesProductTypesProductTypeId(productTypeId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesProductTypesProductTypeIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>>
    export type PatchReferencesProductTypesProductTypeIdMutationBody = PatchProductType
    export type PatchReferencesProductTypesProductTypeIdMutationError = unknown

    /**
 * @summary Update product type
 */
export const usePatchReferencesProductTypesProductTypeId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, TError,{productTypeId: string;data: PatchProductType}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>,
        TError,
        {productTypeId: string;data: PatchProductType},
        TContext
      > => {
      return useMutation(getPatchReferencesProductTypesProductTypeIdMutationOptions(options), queryClient);
    }
    export type deleteReferencesProductTypesProductTypeIdResponse204 = {
  data: void
  status: 204
}

export type deleteReferencesProductTypesProductTypeIdResponseSuccess = (deleteReferencesProductTypesProductTypeIdResponse204) & {
  headers: Headers;
};
;

export type deleteReferencesProductTypesProductTypeIdResponse = (deleteReferencesProductTypesProductTypeIdResponseSuccess)

export const getDeleteReferencesProductTypesProductTypeIdUrl = (productTypeId: string,) => {




  return `http://localhost:3000/references/product-types/${productTypeId}`
}

/**
 * @summary Delete product type
 */
export const deleteReferencesProductTypesProductTypeId = async (productTypeId: string, options?: RequestInit): Promise<deleteReferencesProductTypesProductTypeIdResponse> => {

  const res = await fetch(getDeleteReferencesProductTypesProductTypeIdUrl(productTypeId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteReferencesProductTypesProductTypeIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteReferencesProductTypesProductTypeIdResponse
}




export const getDeleteReferencesProductTypesProductTypeIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, TError,{productTypeId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, TError,{productTypeId: string}, TContext> => {

const mutationKey = ['deleteReferencesProductTypesProductTypeId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, {productTypeId: string}> = (props) => {
          const {productTypeId} = props ?? {};

          return  deleteReferencesProductTypesProductTypeId(productTypeId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesProductTypesProductTypeIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>>

    export type DeleteReferencesProductTypesProductTypeIdMutationError = unknown

    /**
 * @summary Delete product type
 */
export const useDeleteReferencesProductTypesProductTypeId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, TError,{productTypeId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>,
        TError,
        {productTypeId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesProductTypesProductTypeIdMutationOptions(options), queryClient);
    }
    export type getReferencesStatusesResponse200 = {
  data: Statuses[]
  status: 200
}

export type getReferencesStatusesResponseSuccess = (getReferencesStatusesResponse200) & {
  headers: Headers;
};
;

export type getReferencesStatusesResponse = (getReferencesStatusesResponseSuccess)

export const getGetReferencesStatusesUrl = () => {




  return `http://localhost:3000/references/statuses`
}

/**
 * @summary Get all statuses
 */
export const getReferencesStatuses = async ( options?: RequestInit): Promise<getReferencesStatusesResponse> => {

  const res = await fetch(getGetReferencesStatusesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReferencesStatusesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReferencesStatusesResponse
}





export const getGetReferencesStatusesQueryKey = () => {
    return [
    `http://localhost:3000/references/statuses`
    ] as const;
    }


export const getGetReferencesStatusesQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesStatusesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesStatuses>>> = ({ signal }) => getReferencesStatuses({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesStatusesQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesStatuses>>>
export type GetReferencesStatusesQueryError = unknown


export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesStatuses>>,
          TError,
          Awaited<ReturnType<typeof getReferencesStatuses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesStatuses>>,
          TError,
          Awaited<ReturnType<typeof getReferencesStatuses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all statuses
 */

export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesStatusesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postReferencesStatusesResponse201 = {
  data: Statuses
  status: 201
}

export type postReferencesStatusesResponseSuccess = (postReferencesStatusesResponse201) & {
  headers: Headers;
};
;

export type postReferencesStatusesResponse = (postReferencesStatusesResponseSuccess)

export const getPostReferencesStatusesUrl = () => {




  return `http://localhost:3000/references/statuses`
}

/**
 * @summary Create status
 */
export const postReferencesStatuses = async (createStatus: CreateStatus, options?: RequestInit): Promise<postReferencesStatusesResponse> => {

  const res = await fetch(getPostReferencesStatusesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createStatus)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postReferencesStatusesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postReferencesStatusesResponse
}




export const getPostReferencesStatusesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesStatuses>>, TError,{data: CreateStatus}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesStatuses>>, TError,{data: CreateStatus}, TContext> => {

const mutationKey = ['postReferencesStatuses'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesStatuses>>, {data: CreateStatus}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesStatuses(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesStatusesMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesStatuses>>>
    export type PostReferencesStatusesMutationBody = CreateStatus
    export type PostReferencesStatusesMutationError = unknown

    /**
 * @summary Create status
 */
export const usePostReferencesStatuses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesStatuses>>, TError,{data: CreateStatus}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesStatuses>>,
        TError,
        {data: CreateStatus},
        TContext
      > => {
      return useMutation(getPostReferencesStatusesMutationOptions(options), queryClient);
    }
    export type patchReferencesStatusesStatusIdResponse200 = {
  data: Statuses
  status: 200
}

export type patchReferencesStatusesStatusIdResponseSuccess = (patchReferencesStatusesStatusIdResponse200) & {
  headers: Headers;
};
;

export type patchReferencesStatusesStatusIdResponse = (patchReferencesStatusesStatusIdResponseSuccess)

export const getPatchReferencesStatusesStatusIdUrl = (statusId: string,) => {




  return `http://localhost:3000/references/statuses/${statusId}`
}

/**
 * @summary Update status
 */
export const patchReferencesStatusesStatusId = async (statusId: string,
    patchStatus: PatchStatus, options?: RequestInit): Promise<patchReferencesStatusesStatusIdResponse> => {

  const res = await fetch(getPatchReferencesStatusesStatusIdUrl(statusId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchStatus)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchReferencesStatusesStatusIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchReferencesStatusesStatusIdResponse
}




export const getPatchReferencesStatusesStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, TError,{statusId: string;data: PatchStatus}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, TError,{statusId: string;data: PatchStatus}, TContext> => {

const mutationKey = ['patchReferencesStatusesStatusId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, {statusId: string;data: PatchStatus}> = (props) => {
          const {statusId,data} = props ?? {};

          return  patchReferencesStatusesStatusId(statusId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesStatusesStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>>
    export type PatchReferencesStatusesStatusIdMutationBody = PatchStatus
    export type PatchReferencesStatusesStatusIdMutationError = unknown

    /**
 * @summary Update status
 */
export const usePatchReferencesStatusesStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, TError,{statusId: string;data: PatchStatus}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>,
        TError,
        {statusId: string;data: PatchStatus},
        TContext
      > => {
      return useMutation(getPatchReferencesStatusesStatusIdMutationOptions(options), queryClient);
    }
    export type deleteReferencesStatusesStatusIdResponse204 = {
  data: void
  status: 204
}

export type deleteReferencesStatusesStatusIdResponseSuccess = (deleteReferencesStatusesStatusIdResponse204) & {
  headers: Headers;
};
;

export type deleteReferencesStatusesStatusIdResponse = (deleteReferencesStatusesStatusIdResponseSuccess)

export const getDeleteReferencesStatusesStatusIdUrl = (statusId: string,) => {




  return `http://localhost:3000/references/statuses/${statusId}`
}

/**
 * @summary Delete status
 */
export const deleteReferencesStatusesStatusId = async (statusId: string, options?: RequestInit): Promise<deleteReferencesStatusesStatusIdResponse> => {

  const res = await fetch(getDeleteReferencesStatusesStatusIdUrl(statusId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteReferencesStatusesStatusIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteReferencesStatusesStatusIdResponse
}




export const getDeleteReferencesStatusesStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, TError,{statusId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, TError,{statusId: string}, TContext> => {

const mutationKey = ['deleteReferencesStatusesStatusId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, {statusId: string}> = (props) => {
          const {statusId} = props ?? {};

          return  deleteReferencesStatusesStatusId(statusId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesStatusesStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>>

    export type DeleteReferencesStatusesStatusIdMutationError = unknown

    /**
 * @summary Delete status
 */
export const useDeleteReferencesStatusesStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, TError,{statusId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>,
        TError,
        {statusId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesStatusesStatusIdMutationOptions(options), queryClient);
    }
