/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * KS Tech Service Management API
 * API for managing users, Products, and service orders in a service-center / repair business. Designed using API-first principles.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Brands,
  CreateBrand,
  CreateProductType,
  CreateRole,
  CreateStatus,
  PatchBrand,
  PatchProductType,
  PatchRole,
  PatchStatus,
  ProductTypes,
  Roles,
  Statuses
} from '../model';

import { customInstance } from '../../lib/api/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get all roles
 */
export const getReferencesRoles = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Roles[]>(
      {url: `/references/roles`, method: 'GET', signal
    },
      options);
    }




export const getGetReferencesRolesQueryKey = () => {
    return [
    `/references/roles`
    ] as const;
    }


export const getGetReferencesRolesQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesRoles>>> = ({ signal }) => getReferencesRoles(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesRoles>>>
export type GetReferencesRolesQueryError = unknown


export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesRoles>>,
          TError,
          Awaited<ReturnType<typeof getReferencesRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesRoles>>,
          TError,
          Awaited<ReturnType<typeof getReferencesRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all roles
 */

export function useGetReferencesRoles<TData = Awaited<ReturnType<typeof getReferencesRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesRoles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create role
 */
export const postReferencesRoles = (
    createRole: CreateRole,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Roles>(
      {url: `/references/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRole, signal
    },
      options);
    }



export const getPostReferencesRolesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesRoles>>, TError,{data: CreateRole}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesRoles>>, TError,{data: CreateRole}, TContext> => {

const mutationKey = ['postReferencesRoles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesRoles>>, {data: CreateRole}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesRoles(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesRoles>>>
    export type PostReferencesRolesMutationBody = CreateRole
    export type PostReferencesRolesMutationError = unknown

    /**
 * @summary Create role
 */
export const usePostReferencesRoles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesRoles>>, TError,{data: CreateRole}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesRoles>>,
        TError,
        {data: CreateRole},
        TContext
      > => {
      return useMutation(getPostReferencesRolesMutationOptions(options), queryClient);
    }
    /**
 * @summary Update role
 */
export const patchReferencesRolesRoleId = (
    roleId: string,
    patchRole: PatchRole,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Roles>(
      {url: `/references/roles/${roleId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchRole, signal
    },
      options);
    }



export const getPatchReferencesRolesRoleIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, TError,{roleId: string;data: PatchRole}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, TError,{roleId: string;data: PatchRole}, TContext> => {

const mutationKey = ['patchReferencesRolesRoleId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, {roleId: string;data: PatchRole}> = (props) => {
          const {roleId,data} = props ?? {};

          return  patchReferencesRolesRoleId(roleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesRolesRoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>>
    export type PatchReferencesRolesRoleIdMutationBody = PatchRole
    export type PatchReferencesRolesRoleIdMutationError = unknown

    /**
 * @summary Update role
 */
export const usePatchReferencesRolesRoleId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesRolesRoleId>>, TError,{roleId: string;data: PatchRole}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesRolesRoleId>>,
        TError,
        {roleId: string;data: PatchRole},
        TContext
      > => {
      return useMutation(getPatchReferencesRolesRoleIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete role
 */
export const deleteReferencesRolesRoleId = (
    roleId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/references/roles/${roleId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteReferencesRolesRoleIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, TError,{roleId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, TError,{roleId: string}, TContext> => {

const mutationKey = ['deleteReferencesRolesRoleId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, {roleId: string}> = (props) => {
          const {roleId} = props ?? {};

          return  deleteReferencesRolesRoleId(roleId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesRolesRoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>>

    export type DeleteReferencesRolesRoleIdMutationError = unknown

    /**
 * @summary Delete role
 */
export const useDeleteReferencesRolesRoleId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>, TError,{roleId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesRolesRoleId>>,
        TError,
        {roleId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesRolesRoleIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all brands
 */
export const getReferencesBrands = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Brands[]>(
      {url: `/references/brands`, method: 'GET', signal
    },
      options);
    }




export const getGetReferencesBrandsQueryKey = () => {
    return [
    `/references/brands`
    ] as const;
    }


export const getGetReferencesBrandsQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesBrandsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesBrands>>> = ({ signal }) => getReferencesBrands(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesBrandsQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesBrands>>>
export type GetReferencesBrandsQueryError = unknown


export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesBrands>>,
          TError,
          Awaited<ReturnType<typeof getReferencesBrands>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesBrands>>,
          TError,
          Awaited<ReturnType<typeof getReferencesBrands>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all brands
 */

export function useGetReferencesBrands<TData = Awaited<ReturnType<typeof getReferencesBrands>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesBrands>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesBrandsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create brand
 */
export const postReferencesBrands = (
    createBrand: CreateBrand,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Brands>(
      {url: `/references/brands`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBrand, signal
    },
      options);
    }



export const getPostReferencesBrandsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesBrands>>, TError,{data: CreateBrand}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesBrands>>, TError,{data: CreateBrand}, TContext> => {

const mutationKey = ['postReferencesBrands'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesBrands>>, {data: CreateBrand}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesBrands(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesBrandsMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesBrands>>>
    export type PostReferencesBrandsMutationBody = CreateBrand
    export type PostReferencesBrandsMutationError = unknown

    /**
 * @summary Create brand
 */
export const usePostReferencesBrands = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesBrands>>, TError,{data: CreateBrand}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesBrands>>,
        TError,
        {data: CreateBrand},
        TContext
      > => {
      return useMutation(getPostReferencesBrandsMutationOptions(options), queryClient);
    }
    /**
 * @summary Update brand
 */
export const patchReferencesBrandsBrandId = (
    brandId: string,
    patchBrand: PatchBrand,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Brands>(
      {url: `/references/brands/${brandId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchBrand, signal
    },
      options);
    }



export const getPatchReferencesBrandsBrandIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, TError,{brandId: string;data: PatchBrand}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, TError,{brandId: string;data: PatchBrand}, TContext> => {

const mutationKey = ['patchReferencesBrandsBrandId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, {brandId: string;data: PatchBrand}> = (props) => {
          const {brandId,data} = props ?? {};

          return  patchReferencesBrandsBrandId(brandId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesBrandsBrandIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>>
    export type PatchReferencesBrandsBrandIdMutationBody = PatchBrand
    export type PatchReferencesBrandsBrandIdMutationError = unknown

    /**
 * @summary Update brand
 */
export const usePatchReferencesBrandsBrandId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>, TError,{brandId: string;data: PatchBrand}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesBrandsBrandId>>,
        TError,
        {brandId: string;data: PatchBrand},
        TContext
      > => {
      return useMutation(getPatchReferencesBrandsBrandIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete brand
 */
export const deleteReferencesBrandsBrandId = (
    brandId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/references/brands/${brandId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteReferencesBrandsBrandIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, TError,{brandId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, TError,{brandId: string}, TContext> => {

const mutationKey = ['deleteReferencesBrandsBrandId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, {brandId: string}> = (props) => {
          const {brandId} = props ?? {};

          return  deleteReferencesBrandsBrandId(brandId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesBrandsBrandIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>>

    export type DeleteReferencesBrandsBrandIdMutationError = unknown

    /**
 * @summary Delete brand
 */
export const useDeleteReferencesBrandsBrandId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>, TError,{brandId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesBrandsBrandId>>,
        TError,
        {brandId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesBrandsBrandIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all product types
 */
export const getReferencesProductTypes = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProductTypes[]>(
      {url: `/references/product-types`, method: 'GET', signal
    },
      options);
    }




export const getGetReferencesProductTypesQueryKey = () => {
    return [
    `/references/product-types`
    ] as const;
    }


export const getGetReferencesProductTypesQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesProductTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesProductTypes>>> = ({ signal }) => getReferencesProductTypes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesProductTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesProductTypes>>>
export type GetReferencesProductTypesQueryError = unknown


export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesProductTypes>>,
          TError,
          Awaited<ReturnType<typeof getReferencesProductTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesProductTypes>>,
          TError,
          Awaited<ReturnType<typeof getReferencesProductTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all product types
 */

export function useGetReferencesProductTypes<TData = Awaited<ReturnType<typeof getReferencesProductTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesProductTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesProductTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create product type
 */
export const postReferencesProductTypes = (
    createProductType: CreateProductType,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProductTypes>(
      {url: `/references/product-types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProductType, signal
    },
      options);
    }



export const getPostReferencesProductTypesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesProductTypes>>, TError,{data: CreateProductType}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesProductTypes>>, TError,{data: CreateProductType}, TContext> => {

const mutationKey = ['postReferencesProductTypes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesProductTypes>>, {data: CreateProductType}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesProductTypes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesProductTypesMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesProductTypes>>>
    export type PostReferencesProductTypesMutationBody = CreateProductType
    export type PostReferencesProductTypesMutationError = unknown

    /**
 * @summary Create product type
 */
export const usePostReferencesProductTypes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesProductTypes>>, TError,{data: CreateProductType}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesProductTypes>>,
        TError,
        {data: CreateProductType},
        TContext
      > => {
      return useMutation(getPostReferencesProductTypesMutationOptions(options), queryClient);
    }
    /**
 * @summary Update product type
 */
export const patchReferencesProductTypesProductTypeId = (
    productTypeId: string,
    patchProductType: PatchProductType,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ProductTypes>(
      {url: `/references/product-types/${productTypeId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchProductType, signal
    },
      options);
    }



export const getPatchReferencesProductTypesProductTypeIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, TError,{productTypeId: string;data: PatchProductType}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, TError,{productTypeId: string;data: PatchProductType}, TContext> => {

const mutationKey = ['patchReferencesProductTypesProductTypeId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, {productTypeId: string;data: PatchProductType}> = (props) => {
          const {productTypeId,data} = props ?? {};

          return  patchReferencesProductTypesProductTypeId(productTypeId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesProductTypesProductTypeIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>>
    export type PatchReferencesProductTypesProductTypeIdMutationBody = PatchProductType
    export type PatchReferencesProductTypesProductTypeIdMutationError = unknown

    /**
 * @summary Update product type
 */
export const usePatchReferencesProductTypesProductTypeId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>, TError,{productTypeId: string;data: PatchProductType}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesProductTypesProductTypeId>>,
        TError,
        {productTypeId: string;data: PatchProductType},
        TContext
      > => {
      return useMutation(getPatchReferencesProductTypesProductTypeIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete product type
 */
export const deleteReferencesProductTypesProductTypeId = (
    productTypeId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/references/product-types/${productTypeId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteReferencesProductTypesProductTypeIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, TError,{productTypeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, TError,{productTypeId: string}, TContext> => {

const mutationKey = ['deleteReferencesProductTypesProductTypeId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, {productTypeId: string}> = (props) => {
          const {productTypeId} = props ?? {};

          return  deleteReferencesProductTypesProductTypeId(productTypeId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesProductTypesProductTypeIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>>

    export type DeleteReferencesProductTypesProductTypeIdMutationError = unknown

    /**
 * @summary Delete product type
 */
export const useDeleteReferencesProductTypesProductTypeId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>, TError,{productTypeId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesProductTypesProductTypeId>>,
        TError,
        {productTypeId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesProductTypesProductTypeIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Get all statuses
 */
export const getReferencesStatuses = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Statuses[]>(
      {url: `/references/statuses`, method: 'GET', signal
    },
      options);
    }




export const getGetReferencesStatusesQueryKey = () => {
    return [
    `/references/statuses`
    ] as const;
    }


export const getGetReferencesStatusesQueryOptions = <TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferencesStatusesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferencesStatuses>>> = ({ signal }) => getReferencesStatuses(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferencesStatusesQueryResult = NonNullable<Awaited<ReturnType<typeof getReferencesStatuses>>>
export type GetReferencesStatusesQueryError = unknown


export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesStatuses>>,
          TError,
          Awaited<ReturnType<typeof getReferencesStatuses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferencesStatuses>>,
          TError,
          Awaited<ReturnType<typeof getReferencesStatuses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all statuses
 */

export function useGetReferencesStatuses<TData = Awaited<ReturnType<typeof getReferencesStatuses>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferencesStatuses>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferencesStatusesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create status
 */
export const postReferencesStatuses = (
    createStatus: CreateStatus,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Statuses>(
      {url: `/references/statuses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createStatus, signal
    },
      options);
    }



export const getPostReferencesStatusesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesStatuses>>, TError,{data: CreateStatus}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postReferencesStatuses>>, TError,{data: CreateStatus}, TContext> => {

const mutationKey = ['postReferencesStatuses'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReferencesStatuses>>, {data: CreateStatus}> = (props) => {
          const {data} = props ?? {};

          return  postReferencesStatuses(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReferencesStatusesMutationResult = NonNullable<Awaited<ReturnType<typeof postReferencesStatuses>>>
    export type PostReferencesStatusesMutationBody = CreateStatus
    export type PostReferencesStatusesMutationError = unknown

    /**
 * @summary Create status
 */
export const usePostReferencesStatuses = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReferencesStatuses>>, TError,{data: CreateStatus}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReferencesStatuses>>,
        TError,
        {data: CreateStatus},
        TContext
      > => {
      return useMutation(getPostReferencesStatusesMutationOptions(options), queryClient);
    }
    /**
 * @summary Update status
 */
export const patchReferencesStatusesStatusId = (
    statusId: string,
    patchStatus: PatchStatus,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Statuses>(
      {url: `/references/statuses/${statusId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchStatus, signal
    },
      options);
    }



export const getPatchReferencesStatusesStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, TError,{statusId: string;data: PatchStatus}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, TError,{statusId: string;data: PatchStatus}, TContext> => {

const mutationKey = ['patchReferencesStatusesStatusId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, {statusId: string;data: PatchStatus}> = (props) => {
          const {statusId,data} = props ?? {};

          return  patchReferencesStatusesStatusId(statusId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchReferencesStatusesStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>>
    export type PatchReferencesStatusesStatusIdMutationBody = PatchStatus
    export type PatchReferencesStatusesStatusIdMutationError = unknown

    /**
 * @summary Update status
 */
export const usePatchReferencesStatusesStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>, TError,{statusId: string;data: PatchStatus}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchReferencesStatusesStatusId>>,
        TError,
        {statusId: string;data: PatchStatus},
        TContext
      > => {
      return useMutation(getPatchReferencesStatusesStatusIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete status
 */
export const deleteReferencesStatusesStatusId = (
    statusId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/references/statuses/${statusId}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteReferencesStatusesStatusIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, TError,{statusId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, TError,{statusId: string}, TContext> => {

const mutationKey = ['deleteReferencesStatusesStatusId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, {statusId: string}> = (props) => {
          const {statusId} = props ?? {};

          return  deleteReferencesStatusesStatusId(statusId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReferencesStatusesStatusIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>>

    export type DeleteReferencesStatusesStatusIdMutationError = unknown

    /**
 * @summary Delete status
 */
export const useDeleteReferencesStatusesStatusId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>, TError,{statusId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReferencesStatusesStatusId>>,
        TError,
        {statusId: string},
        TContext
      > => {
      return useMutation(getDeleteReferencesStatusesStatusIdMutationOptions(options), queryClient);
    }
